### ISSUE TITLE
BT-722 (EU Funds Name); M-AP; mandatory in all cases?

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#100]
Regarding tendering procedures without EU funding or those with lots without funding and regarding funding is denoted as described in #18, I suggest to set all these happy little Ms on BT-722 to CM.

Reasoning:
- BG-61 must be given even if there are not funds. Explicitly declare there are none. Fine.
- BT-60 (EU Funds) is set to no. This works well. Either for all lots or for the lots without funding, as described in #95.
- Now, BT-722 is still mandatory. I got no text. Sigh.

**Comment by JachymHercher** [comment]
You are of course right, thank you.
