### ISSUE TITLE
BT-52 (Successive Reduction) / DT-120 (No Negotiation Necessary); Description; authoritative announcement?

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#102]
In case a buyer tenders a procedure or a set of lots with Successive Reduction false, does this mean
- he will not under any circumstance add another round of negotiations or if he does will invite all current candidates, or 
- is it an indicative announcement depending on the actual number of offers?
How does this match with BT-120 No Negotiation Necessary? In the case this is _not_ given, will there be at least the participation competition and minimum two negotiation rounds?

**Comment by JachymHercher** [comment]
If BT-52 (Successive Reduction) is given as "no", this means that the buyer will not under any circumstances drop candidates before the final evaluation. (I.e. all candidates are invited to all rounds.)

If BT-120 (No Negotiation Necessary) is given as "no", this means that there will be at least one negotiation round. (If BT-120 is given as "yes" then this means that the winner can be chosen already on the basis of the initial tenders. Essentially, this brings the negotiated procedure close to the open procedure.)

**Comment by tinne** [comment]
To my knowledge, many buyers would like to reserve the option to have a negotiation round once they find out the initial offers are ”not particularly pleasing.“ Do I understand you right (both terms are mandatory) that you will be disallowing so?

(One could surely discussed whether this is fair towards the sellers. The question would be whether they would be forced to abort the procedure and initiate another when they must not.)

**Comment by JachymHercher** [comment]
Not really. Let's say the buyer is running a negotiated procedure. If he chooses BT-120 = Yes, then he can do exactly what you describe. (If they like the offers, they can accept them directly thanks to BT-120. If they don't like them, then they do have to use their right and they can simply negotiate as usual.)

BT-52 isn't linked to this specific issue - it just specifies one property of the negotiations. 

However, it's true that while BT-120 informs about a "possibility" ("the buyer reserves the right"), BT-52 is/sounds more binding ("will be reduced"). I'll check whether BT-52 shouldn't also be worded a bit more openly and get back on that point.

**Comment by JachymHercher** [comment]
Concerning "BT-52", we suggest changing the definition to "The procedure will take place in successive stages. In each stage, solutions or tenders may be eliminated."

**Comment by tinne** [comment]
Sorry for the late reaction. Seems to read all right.
