### ISSUE TITLE
BT-144 (Awarded Reason); AD-AP; why mandatory?

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#103]
As far as I know, if the circumstances require, a buyer may today choose to terminate a tendering procedure. Will they become obliged to publish (or at least report to EUR-OP) a reason for every such termination?

**Comment by JachymHercher** [comment]
This is already the case, see field V.1 of contract award notices. Currently, the two codes used are "No tenders or requests to participate were received or all were rejected" and "Other reasons".  

The information seems quite relevant for reasons of transparency, business planning as well as policy. Just the distinction whether it was a decision of the buyer or the result of the market can be important for businesses (perhaps there's a hole on the market?) as well as policy (depending on the stage, terminating procedures is a very bad practice - if nothing else, companies invest significant resources into preparing tenders for nothing). (BTW: I think that in some countries, buyers are actually not allowed to terminate a tendering procedure; or must give justifications.) 

Also, it enables better enforcement of the direct awards mentioned in the second bullet of https://github.com/eForms/eForms/issues/7#issuecomment-401770888.

**Comment by tinne** [comment]
Not sure whether I understand you correctly:

Regarding direct awards, there is currently no choice with V.1 as `S5-01-00_06 Notice reference` is mandatory and cannot necessarily be given. Thus effectively, in this case there is no choice on reason: it's always that ”no tenders or requests to participate were received or all were rejected.“

**Comment by JachymHercher** [comment]
Which part is not clear?

Frankly, I'm not sure whether the current implementation actually corresponds to the intention in the implementing regulation. As far as I know, the `S5-01-00_06 Notice reference` serves to identify contract notices which have not yet been published but should be deleted, so it's a rather technical matter not really linked to the discussion above...

**Comment by tinne** [comment]
While I support having buyers explain their actions, my question was whether the publication of the reasoning was newly introduced, as in the past the reasoning was mainly for a) technical of b) business reasons, with no further details on the business reasons where the S2.0.8 forms had three plus one checkboxes in F14 / VI.2).
