### ISSUE TITLE
BT-01 (Procedure Legal Basis) / BT-514 (Organisation Country) / BT-09 (Cross Border Law); Description; Determine national legal basis

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#104]
In #18, it was discussed how EU funding can be documented and that this depends on the country of the main buyer. In this context the following related question appeared:

How do I find out the legislation of a notice? For Cross Border Law NULL it must be the Organisation Country of every buyer (organisation with Organisation Role = buyer)?

**Comment by JachymHercher** [comment]
Yes. (More specifically, the EU-level legislation of the notice is the same as of the procedure, which is given by BT-01 (Procedure Legal Basis). This is then transposed into the legal system of the buyer country. If there are buyers from multiple different countries, this is specified in BT-09 (Cross Border Law)).
