### ISSUE TITLE
BT-109 (Framework Duration Justification)

### ISSUE THREAD

**Issue by RolfKewitz** [eForms/eForms#105]
In case of social and other specific services the description of BT-109 (Framework Duration Justification) does not consider the freedom to national law. Currently the description of BT-109 is saying “Justification (such as the subject of the framework agreement) for exceptional cases when the duration of framework agreements exceeds four years in the case of the general procurement directive, seven years in the case of the defence directive, and eight years in the case of the sectoral directive."

Please be aware that in the case of social and other specific services according to article 76 (1) of directive 2014/24/EU german law (§65 (2) VgV) has defined a different threshold for the need to justify the duration of a framework agreement. This means in the case of social and other specific services handled by a german contracting authority there will be a specific justification only when the duration of a framework agreement exceeds six years (which differs from the current description).

**Comment by JachymHercher** [comment]
You are right, this limit does not apply to social services. 

We will change CM to O for PIN CFC social (D24 & D25) and CN social (D24 & D25).
