### ISSUE TITLE
BT-536 (Duration Start Date) / ...  / BT-538 (Duration Code) / BT-109 (Framework Duration Justification); CN-ANY; Duration validation forseen?

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#106]
Will the introduction of eForms introduce rules regarding data on the Duration of framework agreement tenders that an automatic calculation of the total duration can generally been done?

We would like to advise buyers whether the duration of the tendering procedure is planned to be short enough that a Framework Duration Justification is not necessary.

Apart from being lot-specific, this information currently cannot been derived as the notice forms allow for an open interval `[start-date, ?)` or `(?, end-date]` to be specified.

**Comment by tinne** [comment]
(relates to #98)

**Comment by JachymHercher** [comment]
Yes, that is our goal. The CM for BT-109 is supposed to represent conditionality on the notice being a framework, having a particular legal basis, duration, and not being a social service (for the last see #105). 

We don't plan to allow [start-date, ?) or (?, end-date] - unless BT-36 (Duration Period) or BT-538 (Duration Coe) is given. This should cover the exceptions that currently require the open intervals.
