### ISSUE TITLE
BT-08: Organisation Role: not repeatable

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#11]
The organisation role is not repeatable in all the cases. This applies specifically to suppliers. A supplier can be a participant to the tendering procedure, winner, consortium leader, concortium leader, relied upon entity or a subcontractor (not relied upon entity).

BTW: I think it would be very valuable to record also the participants to the tendering procedure as by collecting this information collusive practices could be detected across EU.

**Comment by JachymHercher** [comment]
We agree, the organisation role is not repeatable in all cases. The text of the annex allows this: "Repeatable" means "may be repeated", not "must be repeated". 

Please note this does not apply only to suppliers, as a buyer can also be a central purchasing body. Also, "relied upon entities" and "subcontractors" are (and will be) used in the ESPD, but not in the rest of eForms.

We agree that collecting information about all participants would be very valuable. Furthermore, we note that with eSubmission, this can be done without additional administrative burden. However, we expect that there is not a political consensus on this across all EU member states at this point, and thus plan to introduce the option of publishing this information on TED only as a voluntary extension to eForms.
