### ISSUE TITLE
BT-45 (Rewards Other); Level; Only general?

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#112]
Did you consider moving BT-45 into BG-44 or otherwise adding a per-prize text field?

**Comment by JachymHercher** [comment]
So far, not really. What type of textual information (which couldn't be summarized in BT-45 for all prizes) would be put there?

**Comment by tinne** [comment]
Strictly, none. You could improve structure where in-kind prizes are (partially) used.

Not sure, whether this is often used, though.

**Comment by JachymHercher** [comment]
True, but it's still just a textual description. I would suggest leaving it as it is, unless we find out that it is often used or have some more concrete examples.
