### ISSUE TITLE
BG-701 (Exclusion Grounds); Level; Structuring

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#113]
What is the reason for this strange data structure - did this business group happen to be more complicated? As it just contains one mandatory, non-repeating element, why not remove BT-67 (Exclusion Groups) up to Level +?

And does it really have to be mandatory, even for social contracts?

**Comment by JachymHercher** [comment]
It was done this way just for reasons of consistency. Besides the first few BTs in the spreadsheet (which could be perceived as the notice meta-data) there are no BTs that wouldn't be inside a BG. 

The directive says "conditions for participation", so we are rather inclined to saying yes - even though this general phrase is not 100% clear...
