### ISSUE TITLE
BT-72 (Selection Professiona Activity) / BT-68 (... Economic Financial) / BT-69 (... Technical Professional); Data Type; No longer delegable

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#114]
Can you elaborate on why these three business terms are supposed to be required input and can no longer delegate to information in the procurement documents?

**Comment by JachymHercher** [comment]
These are legally required already under the current forms - see e.g. III.1.1), III.1.2) and III.1.3), of the contract notice. 

(In eForms, it will be possible to replace this by the ESPD.)

**Comment by tinne** [comment]
III.1.1), III.1.2) and III.1.3), of the contract notice have a checkbox ”as stated in the procurement documents.“

**Comment by JachymHercher** [comment]
True, but the text field below still doesn't have an "if applicable" footnote, i.e. the description should still be there. But you are right, it is ambiguous. So from a different side: 
- There's nothing about this information being voluntary in the legal annexes (see e.g. 2014/24/EU Annex V Part C Point 11.)
- When this information can be delegated to the procurement documents, the directives mention it. Compare the above with the award criteria (the same reference as above, just point 18).

**Comment by AlesMMR** [comment]
According to TED validation rules for e.g. F02 boxes III.1.1), III.1.2) and III.1.3) is not mandatory and III.1 and III.2 as whole is not mandatory as well. Therefore I agree that that in reform you are making these boxes mandatory. We would like keep them as it is now voluntarily or at least to keep "as stated in the procurement documents."

**Comment by ognyami** [comment]
I looked at 2014/24/EU Annex V Part C Point 11:
_"11. Conditions for participation, including: [...]
(c) list and brief description of criteria regarding the personal situation of economic operators that may lead to their exclusion and of selection criteria; minimum level(s) of standards possibly required; indication of required information (self-declarations, documentation)."_
How does this text make it mandatory to have 3 separate fields to fill in (BT-72 (Selection Professional Activity) / BT-68 (... Economic Financial) / BT-69 (... Technical Professional)) with text input?
Most of the procedures I know do not use professional activity selection criteria - what are we supposed to type in this case - N/A?
**PLEASE RE-OPEN THIS ISSUE.**

**Comment by JachymHercher** [comment]
The three BTs are all types of selection criteria, so they all fall under the requirement you mention. 

Yes, "N/A", "none", any explicit declaration that such criteria are not used. (See https://github.com/eForms/eForms/issues/183#issuecomment-425095089.)

**Comment by ognyami** [comment]
If everything mentioned in Directive 2014/24/EU Annex V Part C needs to be included in the CNs (without referals to the tender specifications), this would bring a lot of translation costs, especially for the procurement done by the EU institutions, where notices are translated in all official EU languages. But let's accept that the law (Directive) is what it is and we have to implement. Why are we then removing the fax number field from the forms (see item 1 of Directive 2014/24/EU Annex V Part C)?

**Comment by GReaadhsy** [comment]
Information concerning selection criteria provided in this field should be CM (and not M), because it is at the discretion of CAs/CEs to introduce selection criteria or not (optional criteria), depending on the nature and special conditions of each contract. This comment also applies to fields BT-68 & BT-69

**Comment by JachymHercher** [comment]
@GReaadhsy please see #183 (also please feel free to react there)
