### ISSUE TITLE
BT-79 (Performing Staff Qualification); M-AA; three-state logics?

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#115]
The current forms sometimes have a certain strange logic when it comes to optional indicators, thus allow me the following question:

- BT-79 true means the names and professional qualifications of the staff assigned must be given
- BT-79 false means they need not
- BT-79 not given means 
  - they need not OR
  - I do not already know (PIN) OR
  - ~~I have already forgotten OR~~
  - I will not tell you whether I put (will put, had put) that requirements somewhere in the procurement documents?

**Comment by JachymHercher** [comment]
Yes to everything you've said... 

(Optional indicators may be made mandatory at national level.)

**Comment by tinne** [comment]
As discussed in the WebEx, this was meant to be an exclusive or... On the phone, I understand it is ”I will not tell you whether I put (will put, had put) that requirements somewhere in the procurement documents or it's simply irrelevant in this context.“
