### ISSUE TITLE
BT-578 (Security Clearance); Data type; Further information

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#116]
There is currently no way to specify further details on the level of security clearance or the degree of security checks foreseen in the direct context of BT-578 /BT-78.

Did you consider adding such information as a separate text field in BG-705? D 2009/81/EG seems to discuss the topic mainly in the context of BT-69 (Selection Technical Professional) (e.g. Art. 44 (1) j), but to security contracts this might be topic important enough to address specially.

**Comment by tinne** [comment]
As discussed in the WebEx meeting, high clearance or checks levels could impose restrictions for sellers which do not mainly target d`n`s topics. Also, including security requirements into general contract notices might help buyers to address a more general audience with tenders where Art. 2 and 3 D 2009/81/EG do not directly apply.

**Comment by JachymHercher** [comment]
Additional information about the security clearance makes sense. It could be used to specify the required level of security as well as whether it's for the whole team or only for someone, etc. 

We can also add the BT as optional for all other types of notices which have BG-705. It might be used for things like government IT (e.g. often, these systems may have a national security dimension, but will not be linked to defence) and keeping it optional does not impose costs on others.

**Comment by muricna** [comment]
From the ontology side we have a couple of questions:
Does the securiy clearance need to be carried out before submitting an offer or after signature of the contract?
Is the security clearance with regard to access to sites or documents or both?

**Comment by JachymHercher** [comment]
Good point - either is possible. It could be necessary just to access the procurement documents, but it could also be linked to the contract execution. My take away would be that we do not need changes beyond what is described above, because these specifications can exactly be described in the relevant text field.

**Comment by JachymHercher** [comment]
Based on the discussion above, we have:
- Added a new text field, BT-732 (Security Clearance Description), with a description of "Additional information about the security clearance (e.g. which level of security clearance is required, which team members must have it, whether it is necessary already for accessing the procurement documents or only for contract implementation)."
- Extended the BT-578 (Security Clearance) and BT-78 (Security Clearance Deadline) as optional to all types of notice where BG-705 (Others Terms Requirements) occurs.

**Comment by tinne** [comment]
If I understand you right, BT-578 remains mandatory for CN general D81 and CN subco D81 and are otherwise optional. BT-78 are CM for CN general D81 and CN subco D81 and optional else. BT-732 is added in BG-705 (under BT-78) and optional ”from column M to AA.“ Fine with that.

**Comment by JachymHercher** [comment]
Yes for BT-578 and BT-78. Concerning BT-732, we were rather inclined to have it CM under the same conditions as the other two BTs, optional in other cases.
