### ISSUE TITLE
BT-539 (Award Criterion Type); Description; Code list

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#118]
Is the description a direct paraphrase of the code list or will it more closely resemble the directives, like, [price, cost, quality, environmental, social, organisational, service]?

**Comment by JachymHercher** [comment]
Direct paraphrase - we would say these three options cover all the options mentioned in the directive and it is not really necessary to go into a higher level of detail (in particular because the classifications would be quite subjective.)

**Comment by GReaadhsy** [comment]
We consider this field crucial for the procurement procedure, that’ s why it should be mandatory (instead of optional). Furthermore, it is included as obligatory in Annex V Part C point 18 of Directive 2014/24/EU.

**Comment by tinne** [comment]
(Reopened due to @GReaadhsy s question - reclosed as it is duplicated in #192)
