### ISSUE TITLE
BT-165: Winner Size: follow separately

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#12]
I would like to follow micro, small and medium sized companies separately (if this is what TED is to be used for). 

However, this poses a dilemma needing additional instructions:  in a case of a consortium (group of companies) or supplier with its relied upon entitities how should the winner size be calculated? All combined or separately. 

If all combined, the numbers would not be correct: sevaral micro enterprises can participate in a tendering procuder as one entity. All these enterprises are still micro enterprises in other statistics.

**Comment by JachymHercher** [comment]
That is the plan. The codelist for BT-165 should follow the [existing classification]( http://ec.europa.eu/eurostat/web/structural-business-statistics/structural-business-statistics/sme) of micro, small, medium, and large enterprises. 

The problem of consortia etc. is solved by the structure of the annex:

- BT-1701 (Winning Organisation Reference) allows references to multiple organisations in case of consortia, joint ventures, etc. 
- BT-165 (Winner Size) refers to the individual organisation. In other words, in case of a consortium, the information will be given for each organisation separately. 

The issue of relied upon entities is discussed in #37
