### ISSUE TITLE
BT-13 (Additional Information Deadline); Description; Missing legal basis

### ISSUE THREAD

**Issue by RolfKewitz** [eForms/eForms#124]
The term „_Deadline_“ and the explanation of this field „_The time limit for requesting additional information about the procurement procedure._” do no really fit: 
There seems to be no legal justification for a DEADLINE limiting asking questions for unclear points in a procurement procedure. Judges (in Germany) insist of keeping the chance to clarify unclear points until the last minute of a procurement procedure. 
However, a contracting authority may SUGGEST a date until when additional information should be have asked for.
My suggestion is to change name and explanation of BT-13.

**Comment by JachymHercher** [comment]
You are right, this is indeed country specific. The only thing that the EU directives say on this topic (in 2014/24/EU Art. 53(2)) is the following.

> Provided that it has been *requested in good time*, the contracting authorities shall supply to all tenderers taking part in the procurement procedure additional information relating to the specifications and any supporting documents *not later than six days before the time limit fixed for the receipt of tenders*. 

In Czechia, for example, this is interpreted as a hard deadline for asking questions 6 days before the tender submission deadline. 

The logic for this BT was to cover both situations. In the German case, this would mean setting the time limit identical to the tender submission deadline. (This could even be prefilled automatically, thus removing any possible administrative burden. At the same time, this information would still be informative for foreign companies, which may not know the German practice.)

The "suggested deadline" could be considered as an additional type of BT, but givens it's very "soft" nature, I'm wondering whether it is worth it...?

**Comment by AlesMMR** [comment]
In Czech it is 5 working days not 6 :-). But only in case if the tender submission deadline was not shortened.  In that case it is only 4 working days. Therefore we suggest not to add this box in forms. 

If the supplier would like to submit a bid he will read the law anyway therefore he can find the term here.

**Comment by JachymHercher** [comment]
Sorry for the mistake :-) 

We've discussed this a bit more and indeed the regulation depends very much on the country. For example, in Poland, this is transposed as "half of the period for submitting tenders", while in Malta the wording has been taken directly from the directive - so individual authorities can interpret it differently. 

Given that national practices differ and they can be even different authority per authority in some EU countries, we would suggest to keep the field. This information is important and the goal of notices is to simplify information for companies - the less they need to go into the law, the better.

**Comment by tinne** [comment]
Would you foresee the business rules behind the CM field to decide on a per-country basis?

According to the discussion, I would suggest to alter the description to _”The date until which tenderers must or should request any additional information about the procurement procedure.“_

**Comment by JachymHercher** [comment]
As mentioned in #31, the CM is a mistake, it was intended to be an M. We'd say no condition is needed - in some countries, this can be automatically filled in by procurement systems, in other countries, this will differ authority by authority, but it can always be included. 

I'm not sure that the "should", the suggestion of a date, is worth indicating. As mentioned above, if anything, I'd add it is a new BT (to not confuse the "should" and "must"), but only if you find it really extremely useful. Otherwise I'd suggest just sticking with the "must".

From a purely wording point of view, the addition of the verbs also makes it sound a bit like they must or should be asking questions, while what we mean is that they may ask questions, but they must ask them before a given deadline. So I'd be inclined to leave the current definition...

**Comment by JachymHercher** [comment]
Based on the discussions above as well as further feedback received off of GitHub, we will be suggesting to keep one field and making it optional. As with other fields, Member States may make it mandatory at their level.
