### ISSUE TITLE
BT-15 / BT-615 (Documents URL / Documents Restricted): inaccurate description

### ISSUE THREAD

**Issue by Pentadrago** [eForms/eForms#126]
As suggested by @JachymHercher in #69 I'd like to second an description change on BT-15 and BT-615. Im my understanding neither one has to contain the complete procurement documents as they can be split in an unrestricted and an restricted part.

**Comment by JachymHercher** [comment]
Yes, this is true. We will change the descriptions accordingly (both for BT-15 and BT-615).

(In cases such as this one, please feel free to voice the support in the original thread; even if it is already closed.)
