### ISSUE TITLE
BT-19 (Submission Nonelectronic Justification): Codelist

### ISSUE THREAD

**Issue by Pentadrago** [eForms/eForms#127]
Can you give the codelist of this business term?

**Comment by JachymHercher** [comment]
@muricna

**Comment by muricna** [comment]
A common code list should represent Non-electronic communication justification:

Tools, devices, or file formats not generally available
Intellectual property right issues
Buyer would need specialised office equipment
Inclusion of a physical model
Protection of particularly sensitive information

This code list can be used by BT 707 and BT-19.
