### ISSUE TITLE
BT-18 (Submission URL): "address must be direct" 

### ISSUE THREAD

**Issue by Pentadrago** [eForms/eForms#129]
Should it be alright to give the URL to a page containing information about the tendering procedure and the means to participate?

**Comment by JachymHercher** [comment]
Ah, ok, thanks - I didn't get it, sorry. Giving an URL to a webpage for registering for this specific procedure (so that you can then submit a bid) sounds fine. The point is that it should be specific for the procedure, not just a general registration website.
