### ISSUE TITLE
BT-151 (Contract URL); Description; Additional information needed

### ISSUE THREAD

**Issue by Pentadrago** [eForms/eForms#133]
There are some questions we have about BT-151:
In which cases has BT-151 to be filled? 
Is it connected to a contract register used by some countries?
If the information is provided does it have to be unrestricted and complete (e.g. it would not be possible to conceal some information) ?

**Comment by JachymHercher** [comment]
It is optional, so this is up to the Member State / electronic tool provider / authority. 
Yes, we would expect the main use to be to link notices with information in a contract register - if it exists in a given city, region or country. However, it can just as well be used to point to a contract on a municipality's website, for example. 
This is not specified in eForms, i.e. as an optional field, it can point to a redacted or unredacted contract, in any format, etc.
