### ISSUE TITLE
BT-194 (Received Tenders Abnormally Low): only in D25?

### ISSUE THREAD

**Issue by Pentadrago** [eForms/eForms#134]
The handling of tenders, that appear abnormally low, defined in 2014/25/EU Art. 84 is also defined in 2014/24/EU Art. 68 and 2009/81/EC Art. 49. Therefore it should be optional in these cases too.

**Comment by JachymHercher** [comment]
You are of course correct, thank you for pointing it out. We will add the field as optional for all CAN general and CAN social.
