### ISSUE TITLE
WEBINARS CHANGE OF DATE & TIME: 30.8. AND 13.9. MOVED, 21.9. ADDED

### ISSUE THREAD

**Issue by JachymHercher** [eForms/eForms#135]
We regrettably need to reschedule the remaining two webinars. We are also adding a new webinar to discuss any outstanding topics.
- The webinar of 30th August will be moved to Friday 31st August, 10 AM (GMT+2).
- The webinar of 13th September will be moved Friday to 14th September, 10 AM (GMT+2). 
- An additional webinar will be held on Friday 21 September, 10 AM (GMT+2). 

We very much apologize for the changes.

**Comment by JachymHercher** [comment]
The main topic of the webinar of 21st September will be BG-100 (Communication), i.e. rows 151-182 of the spreadsheet. As usual, any other topics brought up by the participants will be discussed as well.

(The webinar replaces the one of 16th August, which was cancelled because of low participation.)

**Comment by jpmckinney** [comment]
I won't be able to able to join the webinar, but I would have asked why BG-100 has a lot reference (BT-13712), whereas the standard forms aren't lot-dependent.

It adds complexity to have different contact points, submission details, etc. for different lots, especially in cases where a supplier can bid on multiple lots. The benefit should outweigh this increase in complexity, but I'm not clear on that the benefit is significant (or in demand by CAs or CEs).

**Comment by JachymHercher** [comment]
Hi @jpmckinney, good question. Can I just ask you to open it as a separate issue?

**Comment by jpmckinney** [comment]
I've created issue #159.
