### ISSUE TITLE
BT-08 (Organisation role); Data type; Possibility to indicate a lead buyer

### ISSUE THREAD

**Issue by manevmi** [eForms/eForms#139]
When several buyers (contracting authorities) are procuring together, one buyer usually takes the lead and manages the procedure. It would be useful to have this type of information (which buyer takes the lead) as structured data in the eForms.

The "lead" contracting authority is already foreseen in Article 165 of the 2018 Financial regulation applicable to the budget of the Union.

**Comment by JachymHercher** [comment]
We agree, we are planning to include this in the BT-08 (Organisation role) codelist (which will be posted in #85). 

However, we are considering whether this function would not be covered by a broader value of "procurement service provider", based on 2014/24/EU Art. 2(17) and 2(15c). Would you have an opinion on that?

(FYI @muricna)

**Comment by manevmi** [comment]
Yes, given that the lead contracting authority is charged with preparation and management of the procurement procedure on behalf of the other participating entities, the term "procurement service provider" can be used too. As long as this important information is captured in a structured way, the term itself does not matter.
