### ISSUE TITLE
BT-23 (Main nature); Description; Add type of contract also at lot level

### ISSUE THREAD

**Issue by manevmi** [eForms/eForms#141]
The type of contract (services, supplies, works) should be added also at lot level - can be derived from the lot CPV or set by the user (in which case the eForm should do a coherence check with the lot CPV).

In this way it will be possible and easy to see  if the "main nature" (contract type at procedure level) has been set correctly: e.g. if the value of the supplies lots is higher than the services lots, the main type must be supplies (as per the PP Directive rules on mixed contracts).

**Comment by JachymHercher** [comment]
The BG-02 (Purpose) is used to inform both about the procedure and lot (see #64). So in principle, BT-23 (Main nature) could be (optionally) provided at lot level. Nevertheless, it is true that we are considering a business rule that this information would be relevant only at the procedure level.

We are not sure of the added value of this information at lot level. As you say, type of contract is essentially just a very general CPV code. As such, it only duplicates information already existing in a CPV code. Consequently, the validation you mention can be done as well using the procedure level Type of Contract and the lot level CPV codes. Similarly, on any website publishing the notice, the type of contract can be recreated for users from the CPV code - if they desire to see it in this format.

(At procedure level, BT-23 is included for two reasons: the field is required by the directives; the information is particularly important for establishing whether a procedure is above or below thresholds.  Neither of these reasons applies at the lot level.)
