### ISSUE TITLE
BT-06 (Strategic Procurement); Description; Typo

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#142]
`inovative`

**Comment by tinne** [comment]
btw., would you mean to say: ”A technical specification, ... criterion, or ... condition... **aimed** to reduce ..., fulfil, and/or buy...?“

**Comment by JachymHercher** [comment]
This is intentional. The field can be in a PIN ("will aim"), in the CAN ("aimed"), etc. We try to resolve this ambiguity with using the present tense as the most neutral one.
