### ISSUE TITLE
BG-137 (Procedure Lot Result); New field; Suggested additional information: Organisation name, ID and bid price for losing bids

### ISSUE THREAD

**Issue by karinmorild** [eForms/eForms#144]
Firms can sustain collusive schemes by dividing the market through abstaining from bidding or mimicking competition through submitting losing bids. Therefore we suggest that data on the value of the bid, the name of the firm and firm ID is collected for firms submitting losing bids as well as those submitting winning bids.

The discussion [BT-08: Organisation Role: not repeatable](https://github.com/eForms/eForms/issues/11) has touched this issue as mr Hercher said that there is a plan to introduce a voluntary extension to eForms. However, I would like to stress that the value for detecting colusive schemes will be limited if only a few submit information about losing bids. Therefore I think there are good reasons, not least from the perspectives of competition for public contracts and good governance of public spending, why the issue should be lifted to be investigated further.

**Comment by JachymHercher** [comment]
Thank you for the comment. We would welcome opinions from other EU countries on this issue and have no problem with putting this on the agenda of the next Economic and Statistical Working Group as well. 

Concerning the use, please note that the extensions (as well as any optional fields) may still be made mandatory at national level, so there can be at least national comparability. However, it is true that cartels can also operate cross borer (whether at a small scale in border region or, in case of concentrated markets, EU-wide) and that cross-country comparisons (of what is typical and atypical) can help discover collusion.

**Comment by JachymHercher** [comment]
@manevmi concerning overall tender prices, whether they are commercially sensitive is probably a case by case question, but I'd expect that more often than not they wouldn't be. Concerning collusion, we've heard this argument in the past, but as far as I know, there isn't really any empirical evidence to support it. (Even the theoretical causal link is not quite clear.) 

For details on both, see http://mythbusting.open-contracting.org/, especially myth 3 and myth 6. (The style of the paper is fairly activist, but the content is actually quite factual.)  

In any case, BG-8 (Not Published) could be used to keep confidential information confidential.
