### ISSUE TITLE
BG-137 (Procedure Lot Result); New field; Suggested additional information: Exact time of bid submission

### ISSUE THREAD

**Issue by karinmorild** [eForms/eForms#147]
Collusive bidding often involves coordination of bid submission or even multiple submissions by the same person, hence analysing the timing of bid submissions can reveal risks of collusion.

**Comment by JachymHercher** [comment]
This seems to be a very narrow use case - just collusion discovery. At the same time, if this information is made publicly available in notices and it's use for this purpose is widely communicated, won't it give away the method to potentially colluding companies? (It's easy for them to avoid this giveaway.)

**Comment by manevmi** [comment]
Exact time of bid submission is already in the eSubmission tools, so, if needed, this data can be extracted from there.  Publishing it will hardly serve the purpose of identifying bid rigging, it will only increase the cost of filling the CAN (even if automatically prefilled with data from eSubmission).
