### ISSUE TITLE
BG-180 (Subcontracting); New field; Suggested additional information in CAN: Consortium members’ name, ID and share of contract

### ISSUE THREAD

**Issue by karinmorild** [eForms/eForms#149]
Bidding and winning in a consortium is a widely used instrument for sharing rents earned from collusion. It is an especially useful enforcement mechanism, as rent sharing is agreed in a formal contract. We thus suggest that data is collected on the name and ID of consortium members as well as each member’s share of the contract.

**Comment by JachymHercher** [comment]
Information on all the members of a consortium can be collected using the repeatable BG-703 (Organisation). All members of the consortia will then be linked to a specific contract using the repeatable BT-1701 (Winner Organisation Reference). 

Concerning each member's share of the contract, this could be added as an optional field or an extension.
