### ISSUE TITLE
BT-137: Purpose Lot Identifier: get's very complicated...

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#15]
Lot identifers are extremely difficult for eTendering platforms as there are platforms that have the lot feature in-built and some that have no lot handing. 

Lot question may need to be discussed in detail.

**Comment by JachymHercher** [comment]
We agree, lots are complicated. We are are happy to discuss them, for example bilaterally or during a webinar. 

From a policy point of view, we note that lots are a very important element of the new directives. For example, see the obligation introduced by 2014/24/EU Art. 46 to justify the decision to _not_ split a procedure into lots. Hopefully, the eTendering platforms do not limit their buyers in splitting into lots, but rather cater only to those procedure which could not be split.
