### ISSUE TITLE
General: The obligation to justify not subdividing contracts into lots

### ISSUE THREAD

**Issue by karinmorild** [eForms/eForms#151]
Article 46 (Directive 2014/24 / EU) provides an obligation to provide an indication of the main reasons for the decision not to subdivide the contract into lots. It seems somewhat inconsistent that there is no corresponding fieldfor this such as the field BT-19 for justifying not using electronic submission of tenders. 

So my question is; Why is there no field for submitting the justification for the decision not to subdivide into lots?

**Comment by JachymHercher** [comment]
According to Article 46, this information needs to be provided in the procurement documents or the individual report in line with Article 84. We are a bit afraid that including it in the notice would create a duplicate obligation, when authorities would need to put it in both the notice and the documents/report. 

However, based on a request in the previous consultation, we are planning to make available an extension that would allow using the contract award notice as the individual report. This extension would also include the lot justification field, as it would allow providing it in the notice while meeting the legal obligation of Article 46.
