### ISSUE TITLE
General: eForms in relation to procurements according to the Public Transport Regulation

### ISSUE THREAD

**Issue by karinmorild** [eForms/eForms#153]
An intention with eForms is to harmonise the terms between the standard forms of the different procurement directives, i.e. making sure that the same name and description is used for the same variable no matter in which standard form it appears.

However, from 3 December 2019, some public service contracts shall be awarded through a competitive tender procedure pursuant to Article 5.3 of the Public Transport Regulation (1370/2007). Sections 7.2 and 7.3 of the Public Transport Regulation also contain rules on publication in the Official Journal of the European Union before and after awarding public service contracts. 

This means that some public transport contracts will be published according to the Classical or Supply Directives while others are published according to the Public Transport Regulation. 

Since the Public Transport Regulation is not mentioned in the spreadsheet my question is: How will publications based on the Classic Directive and the Supply Directive relate to publications based on the Public Transport Regulation? Will these PSC have standardforms in TED? And if so, will there be any harmonisation of terms and standard forms for these publications?

**Comment by JachymHercher** [comment]
@annalisavacca

**Comment by Annalisavacca** [comment]
Sorry for the very late reply.
Indeed, the spreadsheet is for PP Directives. The standard forms for Regulation 1370/2007 exist and will be harmonised by the Publications Office as far as possible in cooperation with DG MOVE.
