### ISSUE TITLE
BT-27 (Estimated Value) / BT-156 (Group Maximum Value) / BT-157 (Group Estimated Maximum Value) / BT-118 (Notice Maximum Value); Description; m.fl. (maximum value in framework agreement(s)); validity and reliability problems

### ISSUE THREAD

**Issue by karinmorild** [eForms/eForms#154]
At first glance these values seems pretty neat and easy but considering them a little more thorough reveals that they might cause problems with validity as well as reliability when processing the data into statistics. And thus pose a risk for incorrect conclusions that in turn may lead to using the wrong actions.

When a central purchasing bodies enter into framework agreements for gods and services intended for other agencies it can be very hard to estimate the value of these framework agreements. For example in Sweden _The National Procurement Services_ enters into framework agreements for goods and services intended for other government agencies. In addition the agencies obtains goods and services covered by the framework agreement by awarding a specific contract following a mini-competition among the economic operators parties to the framework agreement. In these cases the value of the framework agreement is entirely depending on how much goods or services covered by the framework agreement that the government agencies are buying. But it also depends on the prize set in each mini-competition. So the plausible value can have a very wide range, theoretically the total maximum value of the whole framework agreement can be anywhere between zero and indefinitely big.

So, what will happen when these fields are mandatory for the framework agreements CN and CAN? The central purchasing body will have to enter a figure. In some cases there are good condition to estimate the value in the CN and/or the CAN. In other cases it is almost impossible to make a good estimate but a figure will still be entered into the form. This will make the dataset look nice and you can process the data into statistics. **But** if the figure entered retrospectively have very little similarity to the actual outcome we will end up with statistics that have both low validity and low reliability.

I have no good solution for this right now but I think it is an aspect that need to be lifted and investigate further before finalising the definition of these variables and deciding whether they should be mandatory or not.

**Comment by JachymHercher** [comment]
Thank you for the contribution, this is indeed a very complex topic and we very much appreciate your input. Generally speaking, we agree with your description and the fact that this estimation is hard (in some cases very hard). The main question of course is how to do it better. 

Few points:
1. In our opinion, the only way how to have truly accurate information in this area is to publish contracts within framework agreements in line with 2014/24/EU Art. 50 (2). 
2. In the proposal, these fields are (conditionally) mandatory only in the contract award notices. This is for two reasons: 
    - In most EU countries, publishing contract award notices within framework agreements is not mandatory. If the maximum value fields were not mandatory, there would be no information at all about spending within framework agreements. Given their large (and growing) importance, that wouldn't be right from a governance nor transparency point of view.
    - At least in framework agreements with a single company, the company typically commits to only a certain maximum of things it can deliver. At least for this subset of framework agreements, estimating this maximum should be possible.
3. The BTs you mention are about the maximum framework value, not their estimated value. While this lowers the relevance of the information, we proposed it that way precisely to make the (difficult) estimation at least a bit easier. While estimated value includes guessing the demand of the buyers, the maximum value can rely on other factors such as budgetary limitations or the capacity of the companies.

**Comment by GReaadhsy** [comment]
We consider that fields BT-27 and BG-557 should be CM. (The condition for the obligation should only be the fact that at the time of launching the call for competition, maximum value can be estimated by CAs’/CEs’).

**Comment by JachymHercher** [comment]
@GReaadhsy The approaches to using estimated values differs very widely across the EU. In some countries it is mandatory or considered a good practice (because it is taken as a better description of what is required for the market, as well as a sign of the buyer's resources), in others it is discouraged and considered as bad practice (because it is taken as indicating to companies the expected price and thus preventing significantly lower prices from being submitted). For this reason, we leave it optional at the EU level. However, at national level, this field can of course be made obligatory. 

(Concerning conditions, we try to have them as something measurable, i.e. data in another part of the notice. In the case you mention, whether a maximum value _can_ be estimated would not be covered in the notice, so it would be hard to implement as a condition.)
