### ISSUE TITLE
BT-300 (Additional Information); CN/CAN design; intentionally removed?

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#157]
Checking with forms F12 and F13, there is a form field VI.3) Additional Information. Checking with D24, there is Annex V, Part E, 17 / part F, 15 ”Any other relevant information.“ Checking with D25, there is Annex XIX, 16 and Annex XX, 8 (sic).

What is the reason that BT-300 cannot be given in any CN/CAN design notices?

**Comment by JachymHercher** [comment]
You are right, we will add it.
