### ISSUE TITLE
BT-200 / BT-201 (Modification Reason Code / Description) BT-140 (Change Reason); Business Term / Repeatable / Description; Avoid plural

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#158]
There seems to be a mix-up in number:

If a single Modification Reason Code / Description is prescribed, how about changing the description to _”Reason for modifying the contract.“_ Else, change the repeatability to Yes.

If a single Change Reason is prescribed, kindly change the term name appropriately and the description to _”Reason for changes in the notice...“_ Else, change the repeatability to Yes.

**Comment by JachymHercher** [comment]
We agree. We will replace "Reasons" with "Main reason".

**Comment by tinne** [comment]
So, all descriptions change into ”Main reasons for...“ and BT-140 is renamed ”Main Change Reason?“ OK.
