### ISSUE TITLE
BT-26: BT - can other that CPV be used?

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#16]
It is not clear whether ATC is the only additional coding that can be used?

**Comment by JachymHercher** [comment]
Other classifications can also be used, the ATC is only an example.

**Comment by RolfKewitz** [comment]
eCl@ass is another popular classification standard for products and services (which certainly would be appreciated by industry if supported by TED).  However, all entities of TED should be classified (and selectable) by the usage of one common classification standard. If different entities would be classified by different classification standards the ability of a common view will be lost and a general definition of filter criteria would become difficult or even impossible.
Supplemental classification standards in addition to a common standard (like CPV-codes) would be fine.

**Comment by tinne** [comment]
There is a classification system for construction works currently used by German central prequalification organisations which allows enterprises to proof the ability to comply to tenderer requirements with regard to specific professional activities (called ATV codes after the general technical contract conditions for works - Allgemeine Technische Vertragsbedingungen für Bauleistungen).

What would be needed to register this as a classification standard?

**Comment by tinne** [comment]
To improve upon the explanation for the data modelling, kindly consider to edit the descriptions as follows 

Move the following sentences from BT-26 to BG-261: ”The common procurement vocabulary (CPV) classification must be used. Additionally, other classifications... may,... be used.“

Add another sentence to the BG-261 description, ”Different classification schema can be added as different instances of this Business Group, while the CPV-based classification group must always be given.“

**Comment by JachymHercher** [comment]
We will consider it, also in the context of other drafting changes to ensure consistency of what we write in BGs and what in BTs. 

(The second proposal looks good. About the first one I'm not yet sure, because the code gets submited in BT-26 so the explanation - and the legal obligation - should perhaps rather stay there.)
