### ISSUE TITLE
BT-08 (Organization role); Description; Meaning clarification

### ISSUE THREAD

**Issue by UHMYND** [eForms/eForms#160]
Could you please clarify what is meant by organization role in the context of the standard forms?

**Comment by JachymHercher** [comment]
The repeatable BG-703 (Organisation) is used to store information about all type of organisations that are related to a procedure. The BT-08 (Organisation Role) specifies which organisation is which. 

For example, within one notice, one instance of BG-703 may provide information about the buyer, while another instance of BG-703 may provide information about the review body. BT-08 is the field which explains this difference: in the first case, it will have the value "buyer", in the second case the value "review body". 

Is this clear? Would you have any suggestions on how to make this clearer from the definition?
