### ISSUE TITLE
BT-715 (Vehicles) / BT-725 (Vehicles Zero Emission) / BT-716 (Vehicles Clean); Description; Fields purpose

### ISSUE THREAD

**Issue by UHMYND** [eForms/eForms#161]
Could you please elaborate on the reasoning behind including these fields in the standard forms? Not all areas can be monitored through the standard forms. It is somewhat arbitrary to include fields targeted at a single or a few CPV-codes out of the 9 000-10 000 codes available. The monitoring of vehicles is important from e.g. an environmental perspective. We feel that such monitoring should focus on vehicles in use. Monitoring of vehicles in use by the public sector organizations can e.g. be ensured by combining the registration numbers, for vehicles in use by public sector organizations, with information in transport registries on e.g. vehicle environmental standards. We suggest that these fields are removed from the standard forms.

**Comment by UHMYND** [comment]
Thank you for your reply. In general, we support the commitment to better data on procurement, but we also recognize that a balance must be found between the need for better data to inform policy and the administrative burden on those providing it.

**Comment by JachymHercher** [comment]
Thank you for your position, it is noted. Since the decision on these fields is quite political, it will definitely need to be discussed during the official legal procedure.
