### ISSUE TITLE
BT-148 (Received Tenders SME) / BT-147 (Received Tenders EU) /  BT-723 (Received tenders Non EU); Data type, Automated filling

### ISSUE THREAD

**Issue by UHMYND** [eForms/eForms#163]
Could this information be added ex-post by matchning the organizational identifier for a company with information available in business registries based on e.g. annual accounts? This would require information on organizational identifier for all received tenders and not only the winning tender. While this would perhaps increase the administrative burden on buyers/suppliers it would also lower the administrative burden by removing the need for several existing fields. Have these options been explored?

**Comment by JachymHercher** [comment]
This is a good idea and indeed, this is how we believe standard forms should be implemented (=minimum manual input). We note this is a technical question of interconnecting e-tendering systems with APIs of national business registries. 

Please be aware that these fields can already be pre-filled automatically today using the data submitted by tenderers in the ESPD. With mandatory e-submission of bids, this information can also come from well structured tenders. (The ESPD and the e-submission modules can in turn take their data from national registries, bringing us back to the first point.)

**Comment by UHMYND** [comment]
Thank you for replying.

**Comment by JachymHercher** [comment]
Thank you for bringing up the questions - here and in all other other issues!
