### ISSUE TITLE
BG-320 (Winning Tender); New field; Information on all submitted bids

### ISSUE THREAD

**Issue by UHMYND** [eForms/eForms#164]
The standard forms should allow for collecting relevant information on all submitted tenders, not only the winning tender. Such information should e.g. include name and organizational identifier for each tender. The information on all submitted tenders is highly policy-relevant and allows for important analysis on competition for public contracts.  Whats the reasoning behind collecting information only on the winning tender? Which are the main obstacles?

**Comment by tinne** [comment]
Did you consider commenting on #144 and #146?

**Comment by UHMYND** [comment]
Thank you, I´ll be sure to check those .
