### ISSUE TITLE
BT-06 (Strategic procurement); General

### ISSUE THREAD

**Issue by UHMYND** [eForms/eForms#165]
Incuding a field on strategic procurement is highly policy-relevant and likely the best way to monitor progress on political targets on procurement. There is no available information on the proposed code-list? The code-list should be restricted to green, social and innovative procurement. These strategic priorities should be separated and allow for multiple choice. A clear definition is needed for each alternative, followed by practical guidance. The definition should clarify that the strategic priorities means not the procedure in itself but the object of the procurement.

**Comment by tinne** [comment]
Did you check with #40, #93, and #156?

**Comment by UHMYND** [comment]
Thank you, I´ll make sure to check those.
