### ISSUE TITLE
BT-ALL; general; Extension mechanism - how and what?

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#167]
There is some talk about an extension mechanism in these consultation issues, mainly with regard to an ESPD extensions which seems to just wait outside on the landing as well as others for different purposes.

Apart from the technical issues which are obviously to be discussed, I would like to shed a light on the business issues w.r.t. this extension mechanism, e.g.,
- Will there be a set of extensions centrally defined and maintained by the Commission or Publications Office?
- Do you foresee extensions maintained by different, maybe national or non governmental entities?
- The ESPD extension seems to have crucial effect on the validity of a combined data set, e.g. certain business terms of the base set may be replaced by extension data.What are the boundaries until which an extension may modify the base set?
- Will there be means to work with extended / combined data sets for tools agnostic to some or the other extension used and to what extend? How about humans doing such examinations?
- Would different extensions be meant to be combinable in general?

**Comment by JachymHercher** [comment]
The extension mechanism will be part of the implementing regulation, i.e. it will be available for consultation together with the rest of the actual act in November. Technical questions are yet to be decided. Concerning your questions, our provisional approach is the following:
1. Yes. 
2. Not at the moment. The main point of the extensions is to allow publishing additional data on TED. Having extensions managed by other parties and keeping the obligation to publish them on TED sounds like a receipe for problems. However, this doesn't stop national authorities from adding more data to the XML and then using it at national level.  
3. That's mainly a legal question, so I would propose discussing this question when we have the actual wording of the draft act.  
4. I'm not 100% what you mean by tools. Could you specify the question please? (E.g. if we are talking about reception of notices by TED, then it could ignore any information that isn't in the core or in an extension; if we talk about the TED website, then the intention is to publish data from the core and the extensions.)
4. Yes.

**Comment by UHMYND** [comment]
What are the options available to member states concerning the ESPD? Do we understand correctly that there will be two options available, either use the eforms extension or do not (on a national level)? Or is there a third option? An option in which the member state leaves it to the buyers/e-senders to decide (at any given call for tender). Thus resulting in multiple solutions within one member state. Any clarification on this issue would be much appreciated.

**Comment by JachymHercher** [comment]
Technically, there are the two options you mention. 

In a given country, or even a system, both could be implemented, so the third option you mention is also possible. This is a decision to be made at national level - in the national system or in the regulation/certification of ESPD providers.
