### ISSUE TITLE
General; Influence of Member States on field labels used by the TED

### ISSUE THREAD

**Issue by LodewijkIgnatiusTenderNed** [eForms/eForms#168]
One of the improvements according to the introduction document is: 
"Making forms more user-friendly and understandable by giving Member States the freedom to use the field labels that work in their national contexts." Question: does this mean that we as a Member State -if needed- have influence on the terms used in the forms in our lown anguage, as designed by the Publication Office?

**Comment by tinne** [comment]
You might want to take a look at #73.

**Comment by JachymHercher** [comment]
Yes, in two ways:
- For your own tendering systems, you will be able to use any labels, as long as they are in line with the definitions established by the implementing regulation.
- For eNotices, the application run by the Publications Office of the EU, the labels will be put out for consultation, so you will be able to comment on them as well. (And re-use them - if you wish.)

**Comment by LodewijkIgnatiusTenderNed** [comment]
OK, thank you @JachymHercher for your answer and @tinne for your hint. We'll give our review when we recieve the proposal for the terms in Dutch
