### ISSUE TITLE
BT-56: Renewal: description

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#17]
Isn't the renewal also dependent on the estimated / tendered value and thre fact that the contract may not exceed the value more than x % (based on the Directives)?

**Comment by JachymHercher** [comment]
Depends on what exactly we mean by dependent. Is there something we should add to the description? 

According to the directives, the value of options and renewals must already be included in the estimated value of the procedure (see 2014/24/EU Art. 5(1)).  There is no concrete limit on the value of renewals, as they are transparently communicated to the market already in the call for competition (if perceived as contract modifications, they fall under 2014/24/EU Art. 72(1a)).
