### ISSUE TITLE
BT-105 (Procedure Type); Description; Support of SBIR, Open House (processes, not covered by the Directives)

### ISSUE THREAD

**Issue by LodewijkIgnatiusTenderNed** [eForms/eForms#170]
We consider the support in TenderNed of processes, that are not covered by the Directives governing European public procurement, such as SBIR and Open House. Has the Commission covered this need? I notice a discussion in issue https://github.com/eForms/eForms/issues/19#issue-335271677 about BT-88 (Procedure Main Features). But this seems to be only a textfield explaining the procedure. But what about other M or CM BG's and BT's that demand data that is not applicable? Can they be left empty? Or wouldn't it be better to develop another form(s) to distinguish clearly from regular forms covered by the Directives?

**Comment by JachymHercher** [comment]
The current plan is to cover non-directive procedures at a general level: 
- In BT-105 (Procedure Type) there will be one or more choices mentioning that an "Other procedure" is being used. 
- In BT-88, the procedure can be described. 

CM fields should not be a problem - the conditions will state that if "Other procedure" is selected in BT-105, then these fields should not be mandatory. M fields might indeed be a problem - are you aware of fields that would be problematic for a SBIR or an Open House?
