### ISSUE TITLE
BT-504? (Organisation Contact Telefax); all; term missing Intentionally?

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#172]
Yes, the technology of facsimile writers is _somewhat_ dated. Still, people are using it.

When trying to map national contracting forms, I finally saw it: there is no longer a business term for the telefax component of an organisations contact data.

So, here goes the telefax hereditary ticket: it should at least not be buried undiscussed.

**Comment by JachymHercher** [comment]
We suggest leaving it out, because with the current assumed deadline for implementation of early 2022, fax is likely to be used not at all or absolutely minimally. Even compared to today.

**Comment by tinne** [comment]
Oops, alive again since https://github.com/eForms/eForms/issues/114#issuecomment-425146600

**Comment by JachymHercher** [comment]
As it is stated in the annex to the directives and there seems to be demand (see e.g. #200), we will add the field to eForms as optional.

(We note it could be argued that fax as a communication tool is not in line with 2014/24/EU Art. 22, which says that "The tools and devices to be used for communicating by electronic means, as well as their technical characteristics, shall be non-discriminatory, **generally available** and interoperable with the ICT products in general use".)
