### ISSUE TITLE
BT-131 (Deadline Receipt Tenders); Description; Split for second stage procedures

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#173]
In order to run second stage procedures, buyers run two competitions. The first one is usually initiated by a public invitation using a contract notice or a invitation to participate in case of closed competitions.

Here, BT-131 (Deadline Receipt Tenders) use used in the sense of Time limit for receipt of requests to participate. At a later (second) stage, another competition is run under those sellers which successfully passed the first stage.

As the first competition is the only public announcement (if at all), there is no need for TED and the public to have a business term for this second competition deadline. For internal purposes of all participants and organisers of the competition, however, storing also the closed-circle invitation for second stage tenders as eForms data would come in handy. Thus, there should be separate Business Term for the second stage “time limit of request for applications or tenders”.

(This directly corresponds to the ambiguity of current form field IV.2.2) Time limit for receipt of tenders or requests to participate.)

**Comment by JachymHercher** [comment]
This issue is another example of a broader design decision (see #101) about whether different but related concepts, when this is technically possible, should be in one BT. 

We see the main advantage as simplicity: less BTs, less business rules. The main disadvantage is that the meaning of the field needs to be interpreted in context (e.g. to know what BT-131 means in a procedure, I need to know BT-105 Procedure Type). 

Could you please elaborate a bit more on the advantage for the "internal purposes" of having these terms split? For example, we assume that eForms are used as a notification standard, but typically there would be a different "transactional" standard/format used inside an e-tendering system. In such a case, the advantage of splitting the terms is not too clear.

**Comment by tinne** [comment]
Of course, there is quite a lot of form filling (a quick glance at the below-threshold forms in https://github.com/eForms/eForms/issues/169#issuecomment-424779939 suggest some footprint).

Then again, there is some timeline and calendar work to be done in every procurement planning and performance, with some 20 milestones to be set, checked against legal obligations and tracked under modifications and exceptions over the whole time from creation and initial release over EU and national publication of a first notice to actual contract start and procurement document archive.

In general, the dates and times declared in notices for publication or circulation around potential buyers are just projections (views) of these dates, thus, a preliminary notice may show an estimation of the CN publication, an award notice shows the date the contract was concluded and a contract notice the contract duration and the time when tenders are going to be opened. Only the two most important deadlines, submission of requests to participate and submission of tenders are overloaded and thus do not directly map back to the general timeline. Over time and with more complex lots, this might become more complex as some lots may be delayed and deadlines split during the course of a procedure.

Also, kindly regard the terminology and ontology work that is done here has influence on below-threshold terminology over time. Thus Germany discarded their “public procedure type” for the EU “open procedure” and even adopted the official translation “non-open” for restricted procedures. We would thus like to read unified (and separate) business terms for these crucial deadlines as well.

**Comment by JachymHercher** [comment]
From BT-131 (Deadline Receipt Tenders), we have split BT-1311 (Deadline Receipt Requests). The descriptions and legal status has been changed accordingly.
