### ISSUE TITLE
BT-507 (Place NUTS Code); BT-5141 (Place Country); adding an extra text field and change in names

### ISSUE THREAD

**Issue by ognyami** [eForms/eForms#179]
BT-507 (Place NUTS Code) and BT-5141 (Place Country) should allow for some flexibility (possibly by adding a new Text fields in addition to the Code fields), at least for the PINs: in cases of inter-institutional procurement of the EU Institutions, main places of performance could  be the locations of 60+ EUIs situated in a number of countries across Europe. At the stage of the PIN it is not known which exactly all these locations will be. A better solution will be to allow including in the eForms the codes of 2-3 most important locations (known at the stage when the PIN is published) and explain through a text field that the remaining main places of performance will be defined in the CN/the Tender specifications.
Following from the above it will also be better to change the names of the two BTs:
- BT-507: Place NUTS Code -> Main Place(s) NUTS Code(s)
- BT-5141: Place Country -> Main Place(s) Country/-ies

**Comment by JachymHercher** [comment]
We agree about the text field. The same conclusion has also been reached in  https://github.com/eForms/eForms/issues/94#issuecomment-414375525 (together with one other field). 

(Let's discuss the question of "main" in #178.)
