### ISSUE TITLE
BT-09 (Cross Border Law); Data type; text / new BT for Cross Border Procurement (indicator)

### ISSUE THREAD

**Issue by jurakova** [eForms/eForms#180]
Data type for this BT-09 is text, to be able to specify applicable law when buyers from different countries procure together within one procurement procedure.

But it would be even better to have new BT, where buyer could chceck, if procurement is or is not cross border, so this new BT should have Indicator data type.

**Comment by JachymHercher** [comment]
This information is already included in the proposal - only not explicitly. Notices with cross-border joint procurement can be found by searching for notices with more than one buyer (i.e. joint procurement) where the buyers come from at least two different countries (i.e. cross-border).  

While for users (e.g. companies) it would not be practical to search this way, in an IT system it can easily be implemented - clicking a button does the query mentioned above. Is this enough for your purposes?

**Comment by JachymHercher** [comment]
In eForms, we are very much trying to store data only once (i.e. to avoid duplication). This stems from approaching the forms as a data standard (i.e. a tool for transmitting data), not a tool for filling in forms and displaying notices.  

May ask for an example of how this would ease implementation? Our assumption is that costs can be reduced by fewer fields and fewer business rules. As soon as information starts being duplicated (e.g. multiple buyers + a specific indicator), then business rules need to be implemented to ensure coherence between this data. From an implementation perspective, we would expect it is better to avoid this by having information only once. 

We agree that what is more simple for storage, may not be the simplest for filling or reading. However, this should be dealt in the relevant form filling and notice displaying applications. The implementing regulation allows this.
