### ISSUE TITLE
BG-330 (Group Award) / BT-330 (Group Identifier) / BT-1375 (Group Lot Reference); All Notices; Mandatory use

### ISSUE THREAD

**Issue by jurakova** [eForms/eForms#182]
Same as  [#174](https://github.com/eForms/eForms/issues/174), BG-330 is marked as O (optional), but BT-330 and BT-1375 are M (mandatory). If group is only optional, BT under the same BG can´t be M, only CM.

If @tinne is right at [#174](https://github.com/eForms/eForms/issues/174), than we don´t see purpouse to have CMs in spreadsheet.

**Comment by JachymHercher** [comment]
See #174. This notation approach was taken for all mandatory BTs in optional BGs.

**Comment by GReaadhsy** [comment]
We suggest that fields BT-330 and BT1375 should be CM, under the condition that field BG-330 is filled with the indication “YES” by CAs and CEs.

**Comment by JachymHercher** [comment]
@GReaadhsy This is mainly a question of consistent notation (i.e. there are multiple ways to visualise it, any one is good, as long as it is clearly defined and consistent). In the current proposal, BGs do not contain any data directly, they only contain BTs, which is an approach we would like to keep. We will try to clarify this better in the definitions / legal act / introductory documents.
