### ISSUE TITLE
BT-146 (Received Tenders) / BT-148(Received Tenders SME); Description; Clarification concerning tenders received late

### ISSUE THREAD

**Issue by ognyami** [eForms/eForms#184]
In the descriptions of BT-146 and BT-148 (Received Tenders and Received Tenders SME) a clarification is needed if only the tenders received **before the submission deadline** are counted or not ( i.e. if the tenders rejected for being received late are counted for the purposes of the CAN publication).

**Comment by JachymHercher** [comment]
We agree (and we have received similar feedback also off-github). 

Specifically, in BT-146 (Received Tenders), BT-148 (Received Tenders SME), BT-147 (Received Tenders EU) and BT-723 (Received Tenders Non EU) we will replace "tenders" with "tenders received before the submission deadline".

**Comment by ognyami** [comment]
@manevmi - you are right - a clarification is needed if only the tenders received **in accordance with the  submission modalities** are counted or not.

**Comment by JachymHercher** [comment]
Good points. We suggest counting all tenders - indeed, the goal is to measure competition, which starts with the interest of companies. (More information can, if necessary, be given in the BTs discussed in https://github.com/eForms/eForms/issues/146#issuecomment-436935911.) 

In practical terms, for BT-146 (Received Tenders), BT-148 (Received Tenders SME), BT-147 (Received Tenders EU) and BT-723 (Received Tenders Non EU) this means:
- Keeping "tenders", not "tenders received before the submission deadline". 
- To reflect the use of "admissible" in https://github.com/eForms/eForms/issues/145#issuecomment-436934876 and https://github.com/eForms/eForms/issues/146#issuecomment-436935911, we will replace "All tenders received by the buyer must be counted, regardless of whether they have, for example, fulfilled the exclusion grounds and selection criteria." with "All tenders received must be counted, regardless of whether they are admissible or inadmissible."
