### ISSUE TITLE
BT-88: Procedure Main Features (text): what should be here?

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#19]
What should be filled in here?

**Comment by JachymHercher** [comment]
The current description is: 

> Main features of the procedure and information about where the full rules for the procedure can be found. This information must be given when the procedure is not one of those mentioned in the procurement directives. This can be the case for example for concessions, for social and other specific services, and in case of voluntary publication of procurement procedures below the EU procurement thresholds.

Would it be sufficiently clear if we added this? 

> Main features of the procedure __(e.g. description of the individual stage(s))__ and information about where the full rules for the procedure can be found. [...]

An example of what is currently being submitted in this field is for example in [this TED notice](http://ted.europa.eu/udl?uri=TED:NOTICE:7439-2017:TEXT:EN:HTML):  

> IV.1.11) Main features of the award procedure:
Three stage evaluation process consisting of; compliance check, capability and capacity and technical evaluation. Technical evaluation included a range of pass/fail questions and also requirement to meet 50 % of scores available for questions which tested; clinical and service delivery, social value, performance management, workforce and IM&T.
