### ISSUE TITLE
BT-ALL eForms in general

### ISSUE THREAD

**Issue by MBucek88** [eForms/eForms#191]
In general, new eFoms looks like they are more focused to gather information for analytical and statistical evaluation (for purposes of EC to control and evaluate data), rather then for use as standard forms in public procuremet.

explanation: eForms should be with mayor focus to simplify the process of public procuremet and make forms better readable for tenderers and also with less burden to buyers in first place. The gathering of information is also necessary and essential, but should be on second place. 

We understand the need to collect more relevant data from eForms, which curent forms lack, e.g. green public procurement, social procurement, inovation and more. Also it is essential to support SMEs and to support to divide contracts into lots. But the 2nd consultation spreadsheet looks very difficult, confusing and bad readable. We can´t even imagine to implement eForms based on this spreadsheet to make so big burden to buyers and tenderers.      

It would be great to have any compromise between current forms, 1st consultation forms and 2nd consultation spreadsheet eForms.

**Comment by jpmckinney** [comment]
My understanding is that the spreadsheet expresses the data model for this information, not the structure of the forms, and that the purpose of this consultation is to agree on which data elements to collect, and how to define those data elements. As in https://github.com/eForms/eForms/issues/85#issuecomment-426123418, forms can be structured in many different ways to collect the same information. I assume that a future consultation will propose standardized forms.

**Comment by JachymHercher** [comment]
We fully agree and apologize for giving the wrong impression: eForms are in the first place intended for companies, in the second place for public authorities, in the third place for monitoring. Concerning purely statistical and monitoring fields, we are not sure that there are too many. Essentially, these are only the BTs on GPA and the clean vehicles directive in BG-710 and BT-706 (Winner Parent Country). (Arguably, the fields on the number of bids and some information about the buyer and seller fall within this category as well, but those are prescribed by the directive anyway.) Do you consider more BTs as falling into this category? Which ones would you suggest removing? 

Concerning the format, may we ask for some suggestions how to make the spreadsheet better readable? Please note that the descriptions are not the same thing as labels, i.e. the end users may (and should) should read a simpler (and less precise) text than the one which is in the implementing regulation. These texts will be provided by the Publications Office of the EU. 

Indeed, as @jpmckinney mentioned (and as discussed also in https://github.com/eForms/eForms/issues/180#issuecomment-425958273), eForms are about data structure, not the presentation.
