### ISSUE TITLE
BT-539/  Award Criterion Type

### ISSUE THREAD

**Issue by GReaadhsy** [eForms/eForms#192]
We consider field BT-539 crucial for the procurement procedure, that’ s why it should be mandatory (instead of optional). Furthermore, it is included as obligatory in Annex V Part C point 18 of Directive 2014/24/EU.

**Comment by JachymHercher** [comment]
In contract award notices, which correspond to the legal reference you give, the field is already mandatory. (In other notices, it is not mandatory, please see #28 and and #707).
