### ISSUE TITLE
BT-75/ Guarantee Required

### ISSUE THREAD

**Issue by GReaadhsy** [eForms/eForms#194]
Guarantee Required (text) should be changed from optional to CM, depending on national legislation (e.g. according to greek national legislation, it is obligatory for Eos to provide monetary guarantees for certain procedures).

**Comment by JachymHercher** [comment]
We are a bit wary of centrally managing CM conditions per country, as the Publications Office of the EU would have to maintain lists of countries where a gurantee is required, these could change in time, there is no reporting obligation towards the Publications Office, etc. 

Can't this be solved more easily by making the field mandatory at national level? This will be possible.
