### ISSUE TITLE
BT-67 / Exclusion Grounds

### ISSUE THREAD

**Issue by GReaadhsy** [eForms/eForms#195]
We consider that “text” as data type provided in eforms for this field (Exclusion Grounds) is not appropriate, as it causes administrative burden for CAs and CEs, having to describe each exclusion ground. Taking into account that those fields are mandatory, we suggest that there should be a distinct “code” for each exclusion ground. This would help CAs/ CEs and could also provide the Commission with all the necessary data on exclusion grounds.

**Comment by JachymHercher** [comment]
We fully agree. This information should be structured and, in fact, it has already been done so - in the ESPD.  For eForms, the plan is that it will be possible to submit the ESPD _instead_ of BT-67 (and othe relevant fields, see #87). The implementation will depend on the country and solution (see #167). 

For more information, please also see section 4 of the [eForms consultation introduction document](https://github.com/eForms/eForms/blob/master/20180604_eForms_consultation_introduction.docx).
