### ISSUE TITLE
BT-23 (Main nature)

### ISSUE THREAD

**Issue by GReaadhsy** [eForms/eForms#196]
We consider that there should be an additional field having an indication for mixed-contracts. Furthermore, main nature code should be mandatory in all cases and specifically in case of mixed-contract, main nature code should be filled, according to the provisions of the Directives. There also should be a separate field indicating the main nature of each lot.

**Comment by tinne** [comment]
Hm, a mixed contract is a contract where Additional Nature (BT-531) is not empty, is this information is always present - what did I miss?

The separate field indicating the nature of the lots is “secretively hidden”: each lot must have a Classification (BG-261), and the CPV-based classification must always be given, and the nature can be derived from the CPV code. Cf. #136.

**Comment by JachymHercher** [comment]
As explained by @tinne, the current proposal already contains this. (For more information, please also see https://github.com/eForms/eForms/issues/141).
