### ISSUE TITLE
BT-508 (Buyer Profile URL)

### ISSUE THREAD

**Issue by GReaadhsy** [eForms/eForms#197]
We consider that this field should be – at least – CM, except from PIN concerning CPBs, taking into account that, according to Directives, submitting offers via e-procurement platforms is obligatory. In that sense, the relevant organization should provide all the necessary information (procurement documents, procedure, etc) through its website (if available).

**Comment by tinne** [comment]
These web sites can be procurement specific but inter-buyer platforms which provide almost no information on the buyer itself. Is there any regulation on which additional non-procedure-specific information must or should be published?
