### ISSUE TITLE
BT-505  (Organisation Internet Address)/ BT-509 (Organisation eDelivery Gateway)

### ISSUE THREAD

**Issue by GReaadhsy** [eForms/eForms#198]
We consider that these fields should be – at least – CM, except from PIN concerning CPBs, taking into account that, according to Directives, submitting offers via e-procurement platforms is obligatory. In that sense, the relevant organization should provide all the necessary information (procurement documents, procedure, etc) through its website (if available).

**Comment by tinne** [comment]
Kindly consider that these business terms apply to any organisation mentioned in the procurement including review and mediation organisations (cf. #85) so these conditions should at least depend on the Organisation Role (BT-08). Also, procedure specific URLs are given in Communication (BG-100), most notably Documents URL, Documents Restricted URL and Submission URL.

**Comment by JachymHercher** [comment]
@GReaadhsy you are correct that electronic access and submission are mandatory and very important, but as @tinne points out, this is covered by other fields. 

The reason why the BT is not mandatory for all organisations is that we believe this could be problematic for small companies and potentially small buyers (e.g. municipalities) who might not have a website. Do you think this is unlikely?
