### ISSUE TITLE
BT_All eforms / Simplification - Data collection

### ISSUE THREAD

**Issue by GReaadhsy** [eForms/eForms#199]
We would like to stress out that the purposes of data collection / simplification / ensuring data quality, as depicted in the explanatory note, are rather contradictory concepts. Especially as far as simplification concerns, we understand that such a concept should go into the direction of reducing the number of fields as well as minimizing the amount and complexity of the content for each eForm to the absolute minimum information required for eNotification. On the other hand, the need of (additional) data collection having in mind statistical evaluation or monitoring key/performance indicators is contradicting this purpose directly, since this requires new additional and/or more complex fields. In addition, judging from experience derived from our national eNotification system, which is being used in Greece for several different purposes, like  eNotification and special transparency policy and statistics on public procurement:
• data and/or data quality for voluntary or non-mandatory fields, is non-existent or poor
• data quality decreases rapidly with the increase of data fields and/or its complexity

If the purpose of SIMAP is to be shifted, besides eNotification, towards statistics or monitoring key/performance indicators on public procurement, and having in mind the member states’ obligation to provide statistical data/reports on public procurement, it might be worth to consider a “unification” of these processes in order to decrease administrative burden. 

Finally, we consider ESPD and eForms should definitely be linked, so that the same information are filled automatically from ESPD to eForms and vice versa, minimizing that way the administrative burden.

**Comment by JachymHercher** [comment]
Thank you for the comments, we understand your point. Nevertheless, while we agree that sometimes the concepts may be contradictory, we would say that usually they are not. For example, looking at the improvements listed in the explanatory note, most seem to lead to better data quality as well as simplify the life of users (e.g. having clear definitions; harmonizing definitions and data structures; giving flexibility on labels;  harmonizing with the ESPD).  

Concerning purely statistical and monitoring fields, where the trade-off indeed exists, we are not sure that there are too many. Essentially, these are only the BTs on GPA and the clean vehicles directive in BG-710 and BT-706 (Winner Parent Country). (Arguably, the fields on the number of bids and some information about the buyer and seller fall within this category as well, but those are prescribed by the directive anyway.) Do you consider more BTs as falling into this category? 

We agree that optional compliance is low and that more data leads to less quality. To deal with the former, we propose a strict alignment between legally mandatory and technically mandatory fields and we recommend making optional fields mandatory at national level for those countries which consider the information relevant. To deal with the latter, we emphasize the need to prefill fields on behalf of users as much as possible in the e-tendering systems themselves (see e.g. #9, #163)). 

Yes, this is the case, it will be possible to publish ESPD as part of the eForms, thus replacing the corresponding BTs (see #195).
