### ISSUE TITLE
BT-ALL; Level; Meaning of + and ++

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#2]
What is the meaning of + and ++ in the second column, named LEVEL" in the Excel? 

![image](https://user-images.githubusercontent.com/20238848/41226924-ac7e83ba-6d7b-11e8-9fc3-c0c5eb983a18.png)

**Comment by JachymHercher** [comment]
This is the information about being part of groups (about "nesting"). BTs with Level "++" are nested within the closest BG above them with Level "+" ; BTs with level "+++" are nested within the closest BG above them with Level "++".  For example, BT-500 "Organisation Name", BT-514 "Organisation country" (and others) are nested within BG-703 "Organisation". 

Nesting is important mainly for two reasons:

- Repeatability. If a BG is repeatable, then with each repetition of the BG, all the BTs inside it will be repeated as well. 
- Legal Status (O/M/CM) of the nested BTs. If a BG is O(ptional), then this adds one extra layer of optionality to the BTs inside it. For example, BT-9 "Change Description" has the M Legal Status and is within the BG-9 "Change", which has the O Legal Status. This can be read as 'if the notice contains the "Change" business group (which is optional), then it must contain the "Change Description" business term.'
