### ISSUE TITLE
BT-136: Direct Justification Code: term used...

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#20]
This is just a note: Should the text read:

Instead of
 i.e. does not require publishing a call for competition in the Official Journal of the European Union.

this:
i.e. does not require publishing a contract notice in the Official Journal of ...

**Comment by JachymHercher** [comment]
We're not quite sure that would be more accurate. "Call for competition" is broader - besides contract notices (indeed, by far the most common way to call for competition), it also covers PINs used as a call for competition and qualification system notices.
