### ISSUE TITLE
Use of the term Subcontracting

### ISSUE THREAD

**Issue by guascce** [eForms/eForms#205]
Subcontracting is used both to express the conditions allowed for subcontracting  which seems correct and to express the subcontracted parts of a contract in the contract award notice. The subcontracted share is the total value of the subcontracted parts of the contract which can be subcontracted to more subcontracted economic operators. Is it wished to know only the total amount, ?

**Comment by JachymHercher** [comment]
Do we understand it correctly that you are comparing BT-65 (Subcontracting Requirements) and BG-180 (Subcontracting), with the question aiming mainly at BG-180? If yes, then indeed BT-533 (Subcontracting Value) asks only for the total amount to be subcontracted (to anyone; to everyone together). 

The definition is: "Estimated value of the part of the contract that the contractor will subcontract to third parties."
