### ISSUE TITLE
Process questions

### ISSUE THREAD

**Issue by juppsi** [eForms/eForms#206]
We have some questions regarding the process:

1) When will it be decided which syntax (TED xml or UBL) to be used?

2) Is there a project working on defining rules according to the data model? Or, will such a project begin after the work on semantic and ontology are completed? Or, will this project start when the work with the sematic and onthology is done? If so, could you give an approximately date on when this project will begin?

3) When will  schematron files be produced, and by who?

**Comment by JachymHercher** [comment]
1. The Publications Office is currently inclined more towards UBL. (@annalisavacca can provide more information. )
2. Yes, we are working on business rules already. These will be made available for an informal consultation in January, together with the next version of the eForms file. 
3. By the Publications Office of the EU (contract point @annalisavacca). Timing is not yet clear.

**Comment by juppsi** [comment]
@Annalisavacca could you please answer the questions?

**Comment by YvesJo** [comment]
@Annalisavacca is currently unavailable, however  I may confirm the information provided above by @JachymHercher (Annalisa may correct later if I'm wrong):
    1. current orientation is toward UBL, however it will only be confirmed once the evaluation complete.
    3. we will take care of the generation the schematron files and these will be available within the year following the publication of the regulation and not before a bunch of tests and controls are performed.

**Comment by juppsi** [comment]
We have some more questions:

- Service providers in Norway are wondering what kind of technical files will be released in february 2020? Is it XSD or schematron files?

**Comment by juppsi** [comment]
@JachymHercher Could you please answer the question as soon as possible?

**Comment by JachymHercher** [comment]
@juppsi - This is a question on technical implementation, i.e. more for @Annalisavacca & @YvesJo, but if I'm well informed, in 2020 there will be all the files necessary for the implementation, i.e. XSD as well as schematron (+ labels etc.)

Please note that "2020" means "one year from adoption of the act". Regrettably, the adoption of the act is already delayed, so rather than February, we are now talking about May / June. 

(The files may end up being available sooner than one year after adoption, depending on how the technical work goes, but we cannot commit to that.)

**Comment by tinne** [comment]
Would you consider publishing an adjusted schedule to facilitate planning, please? Maybe just add the next milestones to the [README](https://github.com/eForms/eForms/blob/master/README.md)?

**Comment by YvesJo** [comment]
@juppsi - The current orientation is in favour of using schematron. The planning is to provide relevant technical information and files within a year of the corresponding Regulation being published.

**Comment by JachymHercher** [comment]
@tinne, please see page 1 of the new [explanatory note](https://github.com/eForms/eForms/blob/master/1_eForms_feedback_explanatory_note.docx). We apologize for the delay.
