### ISSUE TITLE
BT-135: Direct Accelerated Justification: term used

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#21]
Just a note:
 
Instead of
i.e. does not require publication of a call for competition in the Official Journal of the European Union.

rather
i.e. does not require publication of a contract notice in the Official Journal of...

**Comment by JachymHercher** [comment]
We're not quite sure that would be more accurate. "Call for competition" is broader - besides contract notices (indeed, by far the most common way to call for competition), it also covers PINs used as a call for competition and qualification system notices.
