### ISSUE TITLE
BT-727 Place Services Other

### ISSUE THREAD

**Issue by guascce** [eForms/eForms#213]
I challenge this element for which a code list will be very hard to maintain depending on geographical and political aspects. I would be in favor of not keeping this element and only use the Place Additional information.

**Comment by JachymHercher** [comment]
I'm not sure I understand what it means "hard to maintain depending on geographical and political aspects". Could you elaborate or provide some example please? 

The rationale and use cases for having structured data, not just text, is given in #94. May I perhaps ask you to reply within that thread and close this issue? That way we'll have everything in one place.
