### ISSUE TITLE
eSender class

### ISSUE THREAD

**Issue by paulakeen** [eForms/eForms#214]
While modelling the eProcurement Ontology all the ePO WG members were wondering why, in an eProcurement context, should we keep such a concept.

Can we have your opinion, please?

**Comment by JachymHercher** [comment]
This was apparently a misunderstanding. We thought the BT existed in 2.0.9 forms (and was used by the OP) and thus needed to be included also in eForms. It seems it existed only in 2.0.8 (or earlier) and was deprecated in 2.0.9. 

Consequently, it doesn't need to be in eForms either. 

(Even thought it could be hypothetically used to get insights between data quality and type of eSender...)
