### ISSUE TITLE
BT-761 (Tenderer Legal Form); Description; BT name and description are different in e-po

### ISSUE THREAD

**Issue by guascce** [eForms/eForms#216]
We came up with a different definition in the e-po 

A specific legal entity must be taken up by a tenderer once it has been awarded a contract.
Additional information: this may be applied in the case of groups (e.g. a consortium) where the requirement is that they have to formalise the relationship of the group members as a legal entity itself once the contract is awarded.
This term has been added as a property to the Contract terms concept.

**Comment by guascce** [comment]
Additionnally the property has been renamed 'Contractor legal form Requirement' and we changed slightly our definition to Additional information: this may be applied in the case of groups (e.g. a consortium) where the requirement is that they have to formalise the relationship of the group members as a legal entity itself once the contract is awarded.
WG Approval 2019-01-29, 2019-01-30

**Comment by JachymHercher** [comment]
"Legal form" is used throughout Directive 2014/25/EU, where this requirement comes from, so we would think it is preferable. It also seems better from a "common language" point of view. 

Also, the name seems to use "legal form" but the definition "legal entity". 

In any case, the descriptions of the relevant terms in eForms and the ontology are broadly aligned, so there shouldn't be any problem.
