### ISSUE TITLE
BT-76 (Tenderer Legal Form Description); Unclear description

### ISSUE THREAD

**Issue by guascce** [eForms/eForms#217]
At what time of the procedure is the requirement defining the legal form of the group of economic operator expressed? Can it be part of the Notices?

**Comment by guascce** [comment]
A proposed defition "A constraint concerning the legal form that must be adopted by a tenderer composed of a group of economic operators once it has been awarded a contract."
CONCEPT UNDER DISCUSSION WITH eForms and WG

**Comment by JachymHercher** [comment]
It is defined in the procurement documents, so yes, it can be part of the contract notice. 

The definition uses "legal form", while the definition mentioned in #216 uses "legal entity".

In any case, the descriptions of the relevant terms in eForms and the ontology are broadly aligned, so there shouldn't be any problem.
