### ISSUE TITLE
BT-06 (Strategic procurement); Planning, Competition, DAP, Result; Enforceability of BT

### ISSUE THREAD

**Issue by jadelanava** [eForms/eForms#219]
It would be very useful for studies purposes and data collection that this rubric would be mandatory in all the models, which would allow a uniform information of the total of the procurement.

**Comment by JachymHercher** [comment]
Thank you for the comment, noted. At the end of the day, in line with Annex 2 of the [explanatory note](https://github.com/eForms/eForms/blob/master/1_eForms_feedback_explanatory_note.docx), this will depend on the decisions of the Member States in the relevant advisory committee. 

Please note that at national level, you can make the field mandatory even if at EU level it is optional. This will not ensure cross-border comparability of statistics, but should ensure at least national comparability.

**Comment by tinne** [comment]
> Please note that at national level, you can make the field mandatory even if at EU level it is optional. This will not ensure cross-border comparability of statistics, but should ensure at least national comparability.

With regard to #156 you would then wish to make sure to forbid code value None in those notices, too.

**Comment by JachymHercher** [comment]
@tinne I'm not sure I understand - "None" will always be useful, because there may be procurement procedures with no social, green, and innovative elements, no?
