### ISSUE TITLE
BG-701: Exclusion Grounds

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#22]
Instead of having to provide anything in writing to TED,  I would welcome publishing all the used exclusion grounds from ESPD in all CNs. 

Alternatively, there could be an option: all exclusion grounds are provided in ESPD ...

**Comment by JachymHercher** [comment]
This is indeed the plan - when an ESPD is included in the CN, then BG-701 (Exclusion Grounds) and BG-702 (Selection Criteria) will not have to be provided elsewhere in the CN. It will be possible to provide the ESPD in the eForms as an eForms extension (please see section 4 of the eForms consultation introduction for details).
