### ISSUE TITLE
BT-107 (Technique); Clarification regarding code list value [CODELIST]

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#221]
In the code there is "Contract(s) awarded within a framework agreement or a dynamic purchasing system". It is my understanding that no contract notices are published for reopening of competition in FAs nor DPS. Only CAN is required to be published for each procedure within DPS.

**Comment by JachymHercher** [comment]
Indeed, your understanding is correct. No contract notices are published for re-opening of competition. 

CANs must be published for contracts resulting of a dynamic purchasing system. CANs may be published for contracts resulting from a framework agreement (see Art. 50(2) of Directive 2014/24/EU), which the Commission considers to be a good practice (esp. given the large share of procurement which takes place through framework agreements).

**Comment by jpmckinney** [comment]
Out of curiosity, would the BT-04 Procedure Identifier be different for each contract resulting from a framework agreement / dynamic purchasing system?

**Comment by JachymHercher** [comment]
No, always the same. From an EU law point of view, this is a single procedure (even if the competition is re-opened multiple times; even if multiple contracts are awarded; etc.).

**Comment by ermeio** [comment]
In our Contract register we have a double level of identifier: the identifier for the Framework contract and an identifier for each contract descendng from the framework contract.
This solution can be useful as the buyer and the conditions can differ for the descending contracts, and the characteristics that are specific of the new contract can be referred to the new identifier

**Comment by JachymHercher** [comment]
@ermeio Yes, I think they took the same approach also in the Portuguese BASE. Still, for eForms, we are inclined to have just one - first of all because of the legal reasons mentioned above; second of all because the information on what happens inside a framework agreement is limited at TED level (e.g. the call-offs are not published).
