### ISSUE TITLE
BT-124 (Atypical Tool URL); Repeatable; Why is it "Yes"?

### ISSUE THREAD

**Issue by jpmckinney** [eForms/eForms#226]
What is the reason the Atypical Tool URL is repeatable? The present forms allow only a single URL.

**Comment by JachymHercher** [comment]
Largely based just on a literal reading of the directive's text - "Electronic communication requires the use of tool**s** and device**s** that are not generally available."

To give a very hypothetical example (this field is almost not used, so hard to have a different one), you could probably have one tool for encrypting your message and another one for sending it, or something of that sort.
