### ISSUE TITLE
BG-61 (EU Funds) vs BG-611 (Contract EU Funds)

### ISSUE THREAD

**Issue by jpmckinney** [eForms/eForms#229]
BG-61 simply indicates whether EU funds are involved. BG-611 provides the identifier and name of the EU funds.

Is there a case where it is known that EU funds are involved, but not the identifier or name of the fund? If not, then can these business groups be collapsed into one?

Or, is it the case that EU funds can be involved in a lot, but different funds are used to fund different contracts for that lot (or even multiple funds for one contract)?

**Comment by JachymHercher** [comment]
> Is there a case where it is known that EU funds are involved, but not the identifier or name of the fund?

Yes, this could be the case when publishing the call for competition or, in case of contract award notices, in case of framework agreements. If there were different sources of funds, it might not be clear which funds will be used for which contract in the agreement. (For contract award notices, this should be covered by BR-295 and BR-296, which should start with "If EU Funds (BT-60) is equal to "Yes") 

> Or, is it the case that EU funds can be involved in a lot, but different funds are used to fund different contracts for that lot (or even multiple funds for one contract)?

Yes, exactly. Neither is elegant, but in the end splitting information about EU funds into two BGs seemed perhaps slightly preferable to having both a lot identifier and a contract identifier in BG-61...

**Comment by jpmckinney** [comment]
Sounds good. My issues is closed, but I'll leave open in case there is a business rule to add.

**Comment by JachymHercher** [comment]
BR-296 should be changed to 

If _EU Funds (BT-60) is equal to "Yes"_ and Technique (BT-107) value is different from "Framework agreement without reopening of competition" and "Framework agreement with reopening of competition" and "Framework agreement partly without reopening and partly with reopening of competition", then Contract EU Funds Name (BT-722) is mandatory.

BR-297 should be changed to 

If _EU Funds (BT-60) is equal to "Yes"_ and Technique (BT-107) value is different from "Framework agreement without reopening of competition" and "Framework agreement with reopening of competition" and "Framework agreement partly without reopening and partly with reopening of competition", then Contract EU Funds Identifier (BT-5011) is mandatory.
