### ISSUE TITLE
BT-115 (GPA Usage); Name; Is "Usage" correct?

### ISSUE THREAD

**Issue by jpmckinney** [eForms/eForms#230]
My understanding of GPA is that the semantics are of "coverage" not of "usage". "Coverage" has an implication that the procedure falls under the scope of the GPA and therefore must follow those rules with respect to disclosure requirements, etc. "Usage" has an implication that the CA has some discretion in terms of "using" the GPA. (I'm also not clear that an agreement like the GPA is something that can be "used"). I prefer "Covered by the GPA".

**Comment by JachymHercher** [comment]
Indeed, that is the word used in the description (_"The procurement is covered by the Government Procurement Agreement (GPA)."_), the BT name should be consistent. We will propose renaming GPA Usage. 

In eForms, BT names are typically short, so "GPA Covered" would be probably preferable to "Covered by the GPA"?

**Comment by jpmckinney** [comment]
"GPA Covered" makes sense to me.
