### ISSUE TITLE
Form Type; "Notice change" instead of "Change"? [CODELIST]

### ISSUE THREAD

**Issue by jpmckinney** [eForms/eForms#235]
"Contract modification" is used to clarify that the contract is being modified, not the notice. It would be clearer to name the other form "Notice change" to clarify that it is the notice being changed, not the contract or something else.

**Comment by JachymHercher** [comment]
On one hand, this makes things a bit clearer.

On the other hand, this would lead to a Notice Type (BT-2) of "Notice change notice", which seems a bit confusing (while e.g. "Contract modification notice" sounds ok). This was why we proposed it the way it is, but happy for more opinions.

**Comment by jpmckinney** [comment]
I agree that, with that context, "Change" is better.
