### ISSUE TITLE
Organisation Role; Multiple roles versus narrow roles [CODELIST]

### ISSUE THREAD

**Issue by jpmckinney** [eForms/eForms#236]
The codelist has, for example:

* Procurement service provider
* Procurement service provider (TED eSender)
* Procurement service provider that serves as a contact point

(Separately, it's not clear to me why there is a separate code for TED eSender; in what case is it useful to make the distinction?)

Now, presumably, if an organization fits one of the specialized code, their roles will only include the specialized code, and not the more general first code.

If a data consumer is simply interested in identifying procurement service providers, they will have to test for all three codes (and any future codes that are similarly constructed).

There are two options to ease the use of the data.

The first option is to change the codelist to something like:

* Procurement service provider
* TED eSender
* Contact point

In this scenario, the roles of all procurement service providers would include the first code, making the data consumer's job easier. It also allows other roles to serve as a contact point (I'm not sure if this is desirable or not).

The second option is to keep the present codelist, but to ensure (through business rules) that if one of the specialized codes is set, then the more general code must also be set. This is perhaps the safer option.

The same logic would apply to:

* Winner / Winner (Group leader)

**Comment by JachymHercher** [comment]
Interesting point. The same logic should also apply to any codelist (taxonomy, classification...) which has more than one level, right? If this is the case, then the same approach should be taken also for Technique (BT-107), Buyer Legal Type (BT-11), possibly CPV, NUTS... ? 

You're right this would simplify queries for developers and re-users of the data. I'm wondering whether it really makes a huge difference though. Won't additional business rules (or another solution) add more complexity than requiring people to use "or" statements (or "code starts with 'procurement service provider'")? 

(Concerning the separate code for eSender, this is necessary to know where the notice comes from, e.g. when technical issues need to be resolved. Currently, this information is not published, in the future it will.) 

@paulakeen, @muricna, happy for your views.

**Comment by jpmckinney** [comment]
My understanding of CPV and NUTS is that they already support this use case, because the codes are hierarchical with each lower level in the hierarchy narrowing its upper level, and each number in a code corresponding to a level; in this way, if you're interested in a specific level of the hierarchy, you just compare to the initial numbers that correspond to that level's depth. You don't need to supply the user with a list of codes like "1", "12", "123", "1234", etc.

With buyer roles, is it the case that every contact point is necessarily a procurement service provider? If so, then a prefix-based approach like CPV and NUTS is enough as you suggest; it might be a good idea to describe this approach in guidance, to support data usage. However, if we start having multiple codes like, "Buyer that serves as a contact point", "Central purchasing body that serves as a contact point", etc. then it would make more sense to split "Contact point" into its own role.

For Buyer Level Type, I'm not clear on the levels.

For Technique, I'll open a new issue.

**Comment by JachymHercher** [comment]
When designing it, we took that all contact points would be procurement service providers (psp). This depends on how broadly we understand a "procurement service provider", but so far we are proposing to use it even for buyers who serve as contact points for other buyers (e.g. in the context of joint procurement, see #139). In other words, a buyer who is a contact point would have two roles: "buyer" and "psp - contact point", where being a contact point is why it is a psp.   

Consequently we see an analogy between, for example, Procurement service provider, Procurement service provider (TED eSender) and Procurement service provider that serves as a contact point; and NUTS codes BE2,  BE21, BE22. 

Still, your initial point of harder use persists - instead of just saying "is equal to BE2" the user will need to specify something like "first three characters are equal to BE2". But at the end of the day, requesting this from users is probably simpler overall than requiring more general codes?

**Comment by jpmckinney** [comment]
I agree that, with the additional context, it should be fine to keep the codes as-is, and to suggest to users, in guidance, that if they are interested in procurement service providers, then they should test for the prefix "Procurement service provider", and if they are interested in winners, then they should test for the prefix "Winner".

Perhaps a note can be made with respect to the codelist's management that, if additional specializations of these codes are added in the future, they should keep the same prefix.

This issue can be closed with respect to changes to the codelist.
