### ISSUE TITLE
BR-MULTIPLE; Reference to non-existent "Contact point" Organization Role [CODELIST] [RULE]

### ISSUE THREAD

**Issue by jpmckinney** [eForms/eForms#237]
There is no "Contact point" code in the Organization Role codelist, but several business rules refer to it.

Note: I haven't audited the business rules to check that all referenced codes exist; I just happened to notice this one.

**Comment by jpmckinney** [comment]
This might inform the preferred solution to #236

**Comment by JachymHercher** [comment]
Indeed, some of the codes used in the business rules need to be updated to be in line with the latest codelists. We will change the "contact point" to "Procurement service provider that serves as a contact point".
