### ISSUE TITLE
Buyer Legal Type; Differences from standard forms [CODELIST]

### ISSUE THREAD

**Issue by jpmckinney** [eForms/eForms#238]
The standard forms have:

* Ministry or any other national or federal authority, including their regional or local subdivisions
* National or federal agency/office
* Regional or local authority
* Regional or local agency/office
* Body governed by public law
* European institution/agency or international organisation
* Other

The codelist has:

* Central government authority
* Regional authority
* Local authority
* Body governed by public law
* Public undertaking
* Entity with special rights
* Organisation awarding a contract subsidised by a contracting authority
* Defense Contractor
* International organisation

----

1. There is no "Other" code. Is the codelist now comprehensive, or is there still a use case for "Other"?
1. The original codelist distinguished between authority and agency/office. I don't know what this distinction is, or whether it's worth preserving.
1. I don't see a code corresponding to the old "European institution/agency" code.
1. I don't know what many of the new codes like "Entity with special rights" means. Can a description be provided?
1. "Defense Contractor" should have the same lettercase as other codes (i.e. lowercase "c").

**Comment by JachymHercher** [comment]
1. Having added more values to this codelist, it should now be exhaustive, so "other" is not necessary (even taking into account below-threshold procurement). 
2. We did not find any reliable distinction, it's not worth keeping. 
3. This falls under international organisation (the current forms have an "European institution/agency or international organisation" code). 
4. We will add references to the relevant Articles. 
    - Body governed by public law _(As defined in 2014/24/EU Art. 2(4))_ 
    - Public undertaking _(As defined in 2014/25/EU Art. 4(2))_
    - Entity with special rights _(As defined in 2014/25/EU Art. 4(3))_ (Note @muricna, this should probably be "Entity with special *or exclusive* rights"?)
    - Organisation awarding a contract subsidised by a contracting authority _(As defined in 2014/24/EU Art. 13)_
5. Well spotted, thanks.
