### ISSUE TITLE
Unpublished Identifier; Extra whitespace [CODELIST]

### ISSUE THREAD

**Issue by jpmckinney** [eForms/eForms#242]
There is extra whitespace at the beginning of most codes in the codelist. I understand that this might be the result of copy-pasting from the fields spreadsheet.

**Comment by JachymHercher** [comment]
We'll remove them, thanks.

**Comment by tinne** [comment]
At least with “Unpublished Identifier”, the extra white space seems to be very reasonable to understand the coverage hierarchy / nesting level. This information could be moved to column C, though.

**Comment by jpmckinney** [comment]
Hierarchy should be expressed through a separate column. If whitespace is included in the codes, then implementers might include that whitespace in form submissions, etc. which is not what is intended.

**Comment by JachymHercher** [comment]
As established in https://github.com/eForms/eForms/issues/231#issuecomment-476528411, BT-195 (Unpublished Identifier) will no longer be a code, so the whitespace has no impact on the codelist spreadsheet.
