### ISSUE TITLE
BT-ANY; Data type text; length restrictions

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#245]
The current standard forms restrict the maximum length of many text fields (measured in effective characters) by several different values. It seems (although there is no hint in the official consultation files) that such restrictions might be taken over to eForms.

We propose not to define specific length restrictions on textual business terms.

The sole exception might be if the data type text is used as a vehicle to encode non-unified length restricted data such as postal codes or phone numbers. These could well have a different, more specific data type.

Length restrictions lead to discussions lead to instable grammars. Law courts are running hot about data not included in the notice itself for real or far-fetched length reasons. This discussion should be kept separate from the reasonable requirements to only provide necessary, concise information.

The technical change in the course of the introduction of eForms should be large enough to remove any backward compatibility argument. There could be performance reasons to keep the total data set restricted. This could be remedies by giving a uniform technical length restrictions of, say, 8k or 16k effective characters.

**Comment by JachymHercher** [comment]
We agree that fields lengths are an issue.

The field lengths were implemented for technical reasons at the Publications Office. 

After receiving many complaints on field limits being too short, over the last year, DG GROW has consulted EU countries on their desired field lengths. The results are a significant increase in the limits, but still some limits. 

These should be introduced in eForms as well as the current forms. 

@AnnalisaVacca can provide more information, e.g. on the timing (or on why limits are necessary at all).

**Comment by rantati7** [comment]
If there is a need to limit the length please please keep the length the same for planning, tendering and results stages. Otherwise the data connor be reused.

**Comment by JachymHercher** [comment]
@rantati7, yes, the lengths are planned to be set per field, no differences are planned per type of notice.

**Comment by tinne** [comment]
Member states have huge changes to plan; Publications Office should reconsider.

**Comment by rantati7** [comment]
Karsten, I agree with the huge changes. But this has to be done at some stage. The sooner the better. The Commission / Publication Office needs to set up quite expensive support to MS and system developers. This model can reduce significantly administrative burden BUT only if the implementation is done correctly. Imagine what a bad implementer can do with all this identifiers - making a buyer to fill in identifiers that should be generated in the system...

**Comment by tinne** [comment]
@rantati7 I am not discussing _identifiers_, just texts with no machine readable semantics. Also, simplicity can be a key factor to improvement.

**Comment by JachymHercher** [comment]
@tinne - just to clarify - we should reconsider having "any" limits or reconsider changing limits to the current forms, because MS have huge changes to plan and so they shouldn't spend their time on changing limits now?

**Comment by tinne** [comment]
@JachymHercher I was suggesting that you should abandon the concept of different text lengths for human-readable text data _with_ the introduction of eForms. I was not implying any ideas that the current forms should change somehow, and if you ask me, I would propose to keep them as stable as operable. Funds already spent are gone, the question was if this could help to keep efforts low for future developments by not introducing not directly semantic based per-field restrictions.

**Comment by JachymHercher** [comment]
@tinne As mentioned above, we have discussed this with EU countries and the feedback we received went towards a significant increase in the text limits, but not towards their abolishment. Consequently, we will increase the limits in line with the feedback. More information is available at https://webgate.ec.europa.eu/fpfis/wikis/display/TEDeSender/2019/07/03/New+minor+schema+release.
