### ISSUE TITLE
Change Reason Code; Clarify differences between codes [CODELIST]

### ISSUE THREAD

**Issue by jpmckinney** [eForms/eForms#247]
1. I don't understand the difference between:

* Correction of one or more mistakes
* Correction of a publication error

Isn't a publication error a mistake?

2. With respect to these codes:

* The original notice is cancelled
* The buyer intends to cancel the original notice

Is there often a significant delay between having the intention to cancel a notice, and actually cancelling a notice? Does a buyer ever not follow through with their intention? In other words, what is the use case for "The buyer intends to cancel the original notice"?

The list seems to be taken from this comment: https://github.com/eForms/eForms/issues/47#issuecomment-427338366

**Comment by JachymHercher** [comment]
1. The first one is about mistakes coming from the buyer or the eSender. The second is a "publication error", i.e. a mistake made by TED when publishing the notice. You are right these could perhaps be differentiated more clearly, but we struggled with finding a good wording (also for @muricna). 

2. Apparently, the need to publish the "intention to cancel" stems from some decision of the European Court of Justice.

**Comment by jpmckinney** [comment]
For 1, it might help to state the type of party responsible for the error, like in your explanation.

**Comment by JachymHercher** [comment]
Differentiating the source of the errors has two use cases: 
- Avoiding confusion (e.g. a buyer should understand why a mistake which wasn't in his notice is being corrected)
- Interpreting correctly the data (e.g. if errors in notices are taken as an indication of badly prepared procurement documents, then TED errors shouldn't be included in that). 

Based on the above, it would actually make sense to distinguish three types of errors: buyer, eSender (or other intermediary...), TED. 

What about specifying the codes like this: 
- Correction of one or more mistakes originally made by the buyer 
- Correction of one or more mistakes originally made by the eSender 
- Correction of one or more mistakes originally made by TED

(We added "originally" to try to distinguish between "making the correction" and "making the mistake".)

**Comment by jpmckinney** [comment]
The proposed codes look good to me.
