### ISSUE TITLE
BT-72, 68, 69,79, 87:  Selection - various criterion 

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#25]
If this information is provided in ESPD there should not be a need to provide the information again in eForms.

**Comment by JachymHercher** [comment]
It will not. I suggest merging/continuing this discussion in #23.

**Comment by jpmckinney** [comment]
Noting that BT-79 (Performing Staff Qualification) is not a selection criterion, and is thus not covered by ESPD.
