### ISSUE TITLE
Data type description Date - is time zone useful without time; [ACT]

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#250]
> This field shall contain a date and a time-zone and may contain also more detailed time information.

Suggest to change this to: This field shall contain a date and may also contain more detailed time information and a time-zone.

Rationale: without time information, time-zone information seems to be pretty redundant.

**Comment by JachymHercher** [comment]
Interesting point. You are maybe right - as long as a date is not understood as 00:00/23:59 of a certain day? 

However, changing it to "may" would not be appropriate, as it rather is a "should, if the time information is given". Furthermore, even the original definition of "may also contain more detailed time information" is not quite precise, as it must include this information - if relevant for the particular field. 

Overall, this may be better: 

> This field shall contain a date and more detailed time information (such as time and time-zone), as appropriate.

(This definition is officially written down in the Annex of the Act, in the "Instructions for reading table 2".)

**Comment by tinne** [comment]
Hopefully, we would not need to discuss leap seconds (23:59:60 on some 30/6 or 31/12) here... In fact, in technical specifications I prefer to give durations as Borel sets [00:00 today; 00:00 tomorrow) - except in end user interfaces, where people tend to misunderstand “tomorrow exclusive“.

This is exactly why I proposed to give such information as a pair (date; duration).

(I would, on the other hand, _not_ sharpen the given definition of Duration, “six years”, “two weeks”, and “two and a half day” seem perfectly appropriate.)

**Comment by JachymHercher** [comment]
@tinne that's for @yvesjo (and possibly linked to the discussions in #83, #109, #110).
