### ISSUE TITLE
BT-738 (Notice Publication Date Preferred); Description; Intended Time Frame

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#252]
Thank you for the introduction of a plan date for the OJS publication of a notice.

There is indeed a demand for ahead-scheduled notice publication dates which we currently implement by timing the moment where the notice is send to TED. This extends the case of national holidays mentioned in the BT description, as also scheduled participation and offer open dates, evaluation periods, etc. are taken into account.

Can this date field be used to directly send such notices to TED with an designated publication date in the next few weeks past the dispatch date?

**Comment by JachymHercher** [comment]
> Can this date field be used to directly send such notices to TED with an designated publication date in the next few weeks past the dispatch date?

Yes, this is exactly the use case. So far, there is no limit set on a "maximum preferred publication date" or something like that.

**Comment by tinne** [comment]
No, perfect, thanks. No maximum publication date is fine. Just the description was a bit, ahem, defensive. I would have expected to read:

> If specified, the planned publication date of the notice on TED (e.g. to avoid publication during a national holiday). Defaults to the soonest publication date possible.

**Comment by JachymHercher** [comment]
Concerning the last sentence, that is indeed the idea - if it is left empty, then the notice is published at the earliest possible date (like today). We'd say it's not that necessary to put it in the legal text though, as it is a rather operational issues.

**Comment by YvesJo** [comment]
“Notice Publication Date Preferred” will however be subject to some controls to ensure that it is not posterior to any of the following dates:
•             Deadline Receipt Expressions (BT-630)
•             Deadline Receipt Requests (BT-1311)
•             Deadline Receipt Tenders (BT-131)

When not specified, the value of the “Notice Publication Date Preferred” will automatically be set to the LATEST legally mandated one.

**Comment by JachymHercher** [comment]
@YvesJo Concerning the controls, this makes sense - I'm not sure whether this is explicitly covered by the business rules already? 

Concerning "automatically set", this raises two questions:
- Why latest and not "earliest possible"? I.e. as soon as TED processes the notice, it get published? 
- By "automatically set" you mean that some data would be added to the notice? Or simply that it will be published? I would assume the latter.

**Comment by tinne** [comment]
Please take note that the directives only set minimum time limits, which might be longer e.g. subject to member state law, special cases, etc.

In addition, you would have to check against BT-13 (Additional Information Deadline - no one could request information prior to take note of a yet unpublished notice), and BT-127 (Future Notice) for PIN.

**Comment by JachymHercher** [comment]
Thank you for the explanation, as I understand it, "latest possible" is taken to cater for possible later publication at national level. 

Concerning "automatically set", @YvesJo clarified that this would regard internal OP systems. 

@tinne good point, this should be additional business rules.
