### ISSUE TITLE
BG-61 (EU Funds); Description; Most concrete information until Competition

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#254]
The description to BG-61 EU Funds requires the most concrete information must be given. This formerly referred to BT-722 / BT-5011, which have been moved to Contract (BG-310) / BG-611 (Contract EU Funds).

Am I right to suggest that the second sentence of the description of BG-61 should be retained in BG-611 only?

**Comment by JachymHercher** [comment]
Yes, thank you. We will remove "The most concrete information must be given (e.g. about concrete projects, not just operational programs.)" from BG-61.
