### ISSUE TITLE
Preamble; Proposed extension of paragraph (10); [REGULATION]

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#257]
Text in preample (10) states the following: 

In order to meet different needs at national or regional level, fields that this Regulation establishes as optional at the EU level, may be required mandatorily at national or regional level.

Similarly, it should be stated that: 

the fields that this Regulation establishes as optional at the EU level, may be omitted at national or regional level. 

If there is need to further define this here is a short explanation: there are fields that may not be relevant at member state level and it should be possible to exclude these fields on MS level. This is to ensure best possible usability and to reduce unnecessary administrative burden when a field is not relevant in a MS.

**Comment by JachymHercher** [comment]
Having the possibility to not include optional fields in systems that do not use them is indeed how eForms are intended to work. In other words, if so chosen by the relevant system / national legislator, the end-users do not even need to see the optional fields. This is reflected also in the explanatory note the current forms, which mentions in several places that "in the digital age, optional fields do not imply any costs for countries that do not use them". 

To clarify this point further, we will suggest modifying Rec. 10. We will still discuss the drafting, but it should be something along the following lines (new text in italics): 

> In order to meet different needs at national or regional level, fields that this Regulation establishes as optional at the EU level, _do not need to be displayed to end-users or, on the contrary,_ may be required mandatorily at national or regional level.
