### ISSUE TITLE
BG-705: Other Terms Requirements: should be in ESPD

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#26]
I know that this might be difficult but there should really be a place in ESPD for other requirements (this may also refer to the spance in ESPD where these can be provided and hence shouldnot be repeted in eForms)

**Comment by JachymHercher** [comment]
@ec-mcs is probably a better person to reply to proposals on extending the ESPD.

**Comment by jurakova** [comment]
If BG-705 will stay in eForms (not at the ESPD), that it should be only Optional or CM, not M. It should contain only other requirements if they exist.

**Comment by JachymHercher** [comment]
Outside of the defence directive, the only mandatory BT in BG-705 is BT-77 (Terms Financial). We assume that this BT is always applicable.

**Comment by ec-mcs** [comment]
@rantati7 can you give us some examples of those additional requirements? It would be helping to picture this better. Any improvement would be good ;-)

**Comment by rantati7** [comment]
As there is no space in our structured tendering system to input additional requirements (only ESPD and reqs for what you are buying) we lately had to add these fields. Typically these are related to the contracting term: ‘the supplier has read the terms and conditions, the supplier confirms that it will abide to environmental requirements set in the ESPD for the whole duration of the contract, the supplier confirms that it will follow the social obligations also during the contracting term.” We call these requirements related to contracting period / requirements for submitting a bid. 

We can live without these in notices - it would however, be good to show these also in the notice so that the supplier gets all relevant info already from the notice.
