### ISSUE TITLE
Systematic and authorative mapping between eForms and the ontology conceptual model

### ISSUE THREAD

**Issue by VibekeE** [eForms/eForms#262]
There are differences in the approach between eForms and Ontology, Due to the complexity these differences, the mapping gets complex. Difi propose that the Publication Office takes the responsibility to develop a systematic and authoritative mapping. An examples of differences is "Lots". In the conceptual model Lot is as a sub class of Procurement Project belonging to a procedure. The specific information element for each Lot is connected directly to the Lot. In the eForms on the other hand,  the different information classes contain the Lot ID. Another example is "Classification". In the Ontology CPV code is a specific information element, whilst in the eForms the combination of classification type and classification code provides similar information. This represent different approach of structure.

**Comment by JachymHercher** [comment]
@muricna, @paulakeen 

(This issue builds on #201)

**Comment by paulakeen** [comment]
I agree that the ones responsible for the development of the ontology make sure that the mapping between eForms and the Ontology is possible. But that is currently the situation, is it not? 

As a matter of fact, the data elements in eForms should be viewed as a subset of the ontology, independently of the "approaches" followed by each one: adopting different approaches when modelling is inevitable (and even normal/convient) when the goals (but not the context of use are different), as well explained by @JachymHercher  in #201.

In the case of the eFroms "Classification" and ePO "CPV" there should not be any problem, as the eForms elements "Classification Type" (BT-26), and "Main Classification Code" (BT-262) can be perfectly mapped to the corresponding ePO data element of type Code and its corresponding attributes (listID, listName, listAgencyID, listAgencyName, listVersionID, and any other attribute that may be added as an extension if needed -> in ePO codes are expressed as SKOS-XL, which allows to add any necessary metadata about the list and about any concept coded in the list).

**Comment by muricna** [comment]
The ontology is the reference for eProcurment concepts and to that end the eForms should apply the ontology.

**Comment by guascce** [comment]
I believe that this issue is not only  about technical implementation. The ontology is at the heart of the semantics for procurement.
