### ISSUE TITLE
BT-510 (Organisation Street Name), BT-511 (Organisation Street Number); ANY; Merging BT-510 and BT-511

### ISSUE THREAD

**Issue by VibekeE** [eForms/eForms#264]
Difi suggest suggests to use text string in “Street address”, not dived in “Street name” BT-510 and “Street number” BT-511.

**Comment by JachymHercher** [comment]
We agree.

(Not splitting street name and street number is the approach taken in the eInvoice standard (EN 16931) as well as UBL, OCDS and seems to be [the most general approach](https://stackoverflow.com/questions/929684/is-there-common-street-addresses-database-design-for-all-addresses-of-the-world).)
