### ISSUE TITLE
Change Reason Code; "The original notice is cancelled" [CODELIST]

### ISSUE THREAD

**Issue by jpmckinney** [eForms/eForms#273]
1. Is it the notice that is cancelled or the procurement procedure, i.e. should it be "The procurement procedure is cancelled."?
2. BG-9 (Change) can relate to a specific lot through BT-13716 (Change Previous Lot Identifier).  Shouldn't "The original notice is cancelled" instead be "The original notice or lot is cancelled"?

**Comment by tinne** [comment]
Same regarding “The buyer intends to cancel the original notice _or lot_”.

**Comment by JachymHercher** [comment]
The cancellation could refer to the whole procedure or to one or more lots (as given BT-13716). We suggest changing "notice" to "procurement" (i.e. procedure or lot). For simplicity, we also suggest removing "original" as it perhaps doesn't add much. 

The two codes would then be:
- The procurement is cancelled.
- The buyer intends to cancel the procurement.

**Comment by jpmckinney** [comment]
Sounds good to me.
