### ISSUE TITLE
BT-13716 (Change Previous Lot Identifier); N/A; Reference to other BGs

### ISSUE THREAD

**Issue by jpmckinney** [eForms/eForms#276]
It is useful to scope a change to a specific lot. Would it be even more useful to be able to scope a BG-9 (Change) to a specific other BG? If so, should another BT be added, or should this BT be expanded?

**Comment by JachymHercher** [comment]
Yes, good point. The change could be to any part of the notice. To maintain flexibility, we suggest taking the same approach as in https://github.com/eForms/eForms/issues/275#issuecomment-473923724 (FYI: @yvesjo), i.e. renaming BT-13716 to "Change Previous ~Lot~Identifier" and updating the description to: 

> Identifier of one or more ~lots~ _sections_ within the changed notice. The information in the change cancellation section refers to this _section_~lot~ or these ~lots~_sections_.

**Comment by JachymHercher** [comment]
For clarity and consistency reasons, we suggest renaming BT-13716 to "Change Previous _Notice Section_ Identifier".
