### ISSUE TITLE
BT-06 (Strategic Procurement); Name; Changing the name of the BT

### ISSUE THREAD

**Issue by UlrikaSjoholm** [eForms/eForms#279]
We suggest replacing “Strategic Procurement” with “Secondary Objectives” in order to better reflect the meaning of the field. The understanding of the word strategic differ. A public procurement could be strategic in many ways, not only if innovation, environmental or social aspects are included.

**Comment by JachymHercher** [comment]
We understand your concerns - "strategic" is indeed a very broad word and can easily be understood as also covering other areas of procurement (e.g. professionalisation, effects of joint procurement on shaping the market). 

Regrettably, searching online, "secondary objectives" seem to be used even less than "strategic procurement". Furthermore, by saying "secondary", some could see them as underplaying the importance of green, social, and innovative procurement. 

(One could also argue that, at least for some procedures, green/social/innovative is actually part of the primary objective. Or, from another perspective, looking at EU procurement legislation from a historical point of view, one could argue that the primary and secondary objectives are "market integration" and "value for money", while  green social innovative would be "tertiary" goals.)  

Consequently, in the absence of another candidate (and we've tried hard to come up with one), we do not at this point see a better option than "strategic". However, we are happy for further proposals or to discuss it with the advisory committee on public procurement.

**Comment by UlrikaSjoholm** [comment]
Thank you for the response. Another porposal could be "Sustainability and innovation".

**Comment by JachymHercher** [comment]
Thank you for the comment. It is not bad, but we're worried that "sustainability" may be understood by some users (and in some languages...) as only "green", not as "social". 

Given the addition of the new fields mentioned in https://github.com/eForms/eForms/issues/259#issuecomment-481315769 into the proposal, we will explicitly discuss these fields during the meeting of the advisory committee on public contracts, so perhaps more proposals will come from there.
