### ISSUE TITLE
BG-38 (and all under this heading): shouldn't this be also in CN?

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#28]
Shouln't this information be provided also in CN - not just CAN?

**Comment by JachymHercher** [comment]
It can be provided optionally. According to the directives (see e.g. 2014/24/EU Art. 29(6); Annex V Part C point 18) it is mandatory only in CANs. 

Same as for other fields, Member States can make award criteria information mandatory at national level (e.g. with the aim to reduce possible duplication between the notice and the procurement documents).
