### ISSUE TITLE
BT-08 (Organisation roles); Missing values in code list [CODELIST]

### ISSUE THREAD

**Issue by UlrikaSjoholm** [eForms/eForms#280]
It appears that consortium leader and consortium member are missing from the codelist.

**Comment by JachymHercher** [comment]
The Organisation Role codelist contains the value Winner (Group leader). This is intended to be used for a leader of a consortium, joint venture, etc. 

We're not sure whether consortium member needs to be identified explicitly - if an organization is a Winner and it is not a Winner (Group leader), it is implicitly just a consortium member.

**Comment by jpmckinney** [comment]
I agree with the use of existing codes. This can perhaps be described in an FAQ or other guidance.

**Comment by paulakeen** [comment]
We have been mapping the eForms BT-08 "Organisation Role" with the actors that play a role in eNotification and eAccess and that are directly or indirectly descendants of the W3C org:Organization:

[Organisation_role_mapping_v1.0.xlsx](https://github.com/eForms/eForms/files/2971210/Organisation_role_mapping_v1.0.xlsx)

There are two main roles that do not exist in eForms: Economic Operator and Tenderer.

In the ePO codelist EO Role Type we have also the codes:

* "Sole Contractor", and 

* "Member of a Group", referring to an Economic Operator that belongs to a group, e.g. to a Consortium, and that is not the lead of the group. 

We wonder whether these roles are not needed in eForms.

**Comment by JachymHercher** [comment]
Thank you for the comparison. However, as far as we can see, they are not. 
- Economic Operator (who is not a Winner) is not needed anywhere in the current forms. (In the ontology, this can be relevant e.g. when publishing information on who asked a question.)
- Tenderer (who is not a Winner) is not needed anywhere in the current forms. (In the ontology, and perhaps in a future update of eForms, it would be useful to publish information about all Tenders and Tenderers, not just the Winning Tender and Winner.) 
- Sole Contractor - we assume this means there is no consortium, joint venture, etc.? In eForms, this is modelled implicitly, i.e. if there aren't multiple Winners, the is just one, sole Winner. 
- "Member of a Group" - modelled implicitly, see https://github.com/eForms/eForms/issues/280#issuecomment-472806666.

**Comment by jpmckinney** [comment]
If "Sole Contractor" means "Sole Trader" (i.e. an individual), then that's a semantic difference, though not one that eForms cares about either, as far as I know.

**Comment by JachymHercher** [comment]
@jpmckinney Indeed, if it means "Sole Trader" then it would rather be a possible subcategory for BT-165 (Winner Size) - a category smaller than micro. However, according to the colleagues responsible for SME policy, differentiating micro and "sole trader" is not really a high priority.

**Comment by paulakeen** [comment]
The code list containing "Sole Contractor", "Group Lead", "Member of a Group", "Relied-on" and "Not-Relied-on", etc. was taken from ESPD to distinguish the type of economic operator for which an individual ESPD is needed and so getting the maximum detailed information about any of them.

Hence, in that context, the meaning of "Sole Contractor" would be more "Sole Tenderer", and not "Sole Trader" (if "Trader" implies "Winner").

**Comment by tinne** [comment]
@paulakeen Maybe use the wording “sole proprietor” instead of “some trader” to better account for non-trade (in the sense of retail, gross, and foreign sale) people?
