### ISSUE TITLE
BT-148 (Received Tenders SME), BT-165 (Winner Size); Description; Guidance about SMEs

### ISSUE THREAD

**Issue by UlrikaSjoholm** [eForms/eForms#281]
The definition of SMEs is not easily applicable in practice. In Sweden, this is done manually. To assure that the same assessments are made in these fields, help texts will be necessary. In order to obtain comparable data, a simplification of the definition should be considered. In Sweden, we use other sources to get information in this aspect to obtain higher quality.

**Comment by JachymHercher** [comment]
We agree that the definition should be simplified - a revision of the definition is currently underway. As far as possible, we would also suggest trying to reduce manual input of this information. 

(Please see also https://github.com/eForms/eForms/issues/190#issuecomment-427307321, https://github.com/eForms/eForms/issues/162#issuecomment-423249890, #163).
