### ISSUE TITLE
BT-147 (Received Tenders EU), BT-723 (Received Tenders Non-EU); Description; Guidance about definitions

### ISSUE THREAD

**Issue by UlrikaSjoholm** [eForms/eForms#283]
It will be easier for practitioners to determine whether or not a tenderer is to be considered as a EEA-tenderer if there is a help text about branches and companies that are part of a larger group.

**Comment by paulakeen** [comment]
If the ESPD structured XML document was used, the possibility of identifying where each member of the group (Consortium, Joint Venture, etc.) is from could be "calculated" automatically. 

The ESPD-EDM (Exchange Data Model) specifies that the group lead has to specify who are the members of the group. For this a UBL class `cac:EconomicOperator` is provided  with sufficient data elements to identify the economic operator, its role, its representatives, physical location, officially registered address and other.

**Comment by JachymHercher** [comment]
@UlrikaSjoholm The definitions say "tenderers registered in XYZ". Isn't this enough to solve the ambiguity about branches and companies which are parts of a larger group? 

(There is still of course ambiguity in what "majority of the work" means, but that it is primarily asking just for a rough estimate. If it was to be precise, it would need a rather sophisticated economic and legal analysis, going much above the scope of eForms.) 

@paulakeen This seems to be the same approach as eForms - every member of a consortia/joint venture is indicated?
