### ISSUE TITLE
BT-75 (Guarantee Required Description); Description; Inconsistent term inside the definition

### ISSUE THREAD

**Issue by paulakeen** [eForms/eForms#284]
The term "bid" in the definition should be replaced by "tender". This definition is the only place where "bid" is used, whilst "tender" is the term used in many other different places.

Additionally, in the ePO ontology the decision was made to use only and always "tender", which has been defined as the "Information submitted by the economic operator to specify its offer in response to the call for tender." (ePO WG approval 07/11/2018)

**Comment by JachymHercher** [comment]
Thanks for noticing!
