### ISSUE TITLE
BT-132 to 134; Level; BTs should be grouped in a BG

### ISSUE THREAD

**Issue by paulakeen** [eForms/eForms#287]
As they are now, the BTs 132 to 134 cannot be associated to a specific Lot, which is a business requirement. 

If they were grouped in a "Repeatable YES" BG (now the BTs are Repeatble NO") it could be used in a very flexible way, e.g. different places for the opening of one or more lots (or procedures for that matter) can be important when the tenders are to be open in different departments, organisations or countries (which can be the case when the tenders are translated in different languages and need to be open by different officers distributed geographically (e.g. by different responsible roles, from different departments, in different MS, at different dates and times).

**Comment by jpmckinney** [comment]
I had read these as being part of BG-102 (Submission Terms), which is repeatable and which has a repeatable BT-13719 (Submission Lot Identifier) to identify to which lots the terms apply.

**Comment by paulakeen** [comment]
You're absolutely right! This is also a good feed-back for the ePO. 

many thanks

**Comment by paulakeen** [comment]
And yet there's still this other aspect about how to specify multiple different opening places and date-times for one same lot ..., which would imply the "repeatability" of the opening-related fields.

**Comment by JachymHercher** [comment]
A clarification is in order here: these fields are not intended to describe the internal procedures of the contracting authority, but rather to inform the public in case a public opening is being held (this is typically used in open procedures). 

The purpose of informing the public about the opening place and time is transparency. All the tenders submitted for a particular lot are opened at the same time and place, while inviting the public, to make it transparent that no documents get "lost" from the envelopes, that none of the envelopes was opened preliminary (and the content potentially leaked to a competition), etc. Keeping this in mind, I'm doubtful that multiple opening places per single lot would fulfill this use case. 

However, we should probably clarify the meaning of this fields, e.g. by replacing "opening" by "public opening". 

Two other general points are also worth keeping in mind, not to spend too much time on this point: 
- These fields were very meaningful under paper submission. With eSubmission, their importance is very low. (Even though they may still be used for below-threshold; procurement with non-electronic submission; etc.) 
- We propose that the lot identifiers in the spreadsheet are not part of the Implementing Regulation. Instead, we consider them as a technical matter linked to format, which can be solved in the schema itself. This means the identifiers in the spreadsheet can be treated as indicative only, and the final solution can be set later and can be different than one indicator per BG (e.g. such as in the ESPD, where lot identifiers are an attribute of each field).
