### ISSUE TITLE
BT-107 (Technique); Any; Unnecessary BT

### ISSUE THREAD

**Issue by paulakeen** [eForms/eForms#289]
The code list Technique was considered not necessary there should be one code list for framework agreement type.

For the information on DPS:

Dynamic purchasing system (only usable by buyers listed in this notice)

Dynamic purchasing system (also usable by buyers not listed in this notice)

It is necessary to know to which notices the information refers to, would it be possible for the buyers listed to be changed from CN to CAN.  It also noted that  eAuction can be used in DPS and DPS as well as eCatalogues can be used in framework agreements (FA) which makes modelling and using codes as currently foreseen in eforms difficult.  There was a question as to whether DPSs could really be used for non-listed buyers.

For the information:
Contract(s) awarded within a framework agreement or a dynamic purchasing system this information can be obtained via the purchase contract in the ontology.

For the information on eAuction see the comment on DPS – e Auction can be used in FA and DPS

For information on eCatalogue:  
Electronic catalogue must be submitted with the tender
Electronic catalogue may be submitted with the tender
The code list permission can be linked to eCatalogue

**Comment by jpmckinney** [comment]
Please see the discussion in #251. My last comment tried to align the ePO and eForms approaches.

**Comment by JachymHercher** [comment]
Indeed, I would suggest to continue this discussion in @251.
