### ISSUE TITLE
BT-107: Techique: is electronic ordering a technique?

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#29]
Does the code list here consist of multiple choice options? 

Electronic ordering can be used on conjunction with all. The same with electronic auctions (except for specified types of services).

**Comment by JachymHercher** [comment]
Yes, it is a repeatable field. The notice can contain information about multiple options (e.g. "framework agreement with reopening of competition" and "electronic ordering"). Essentially, this is equivalent to multiple yes/no questions.

**Comment by JachymHercher** [comment]
Correction: Based on further reflections, we have decided to take electronic invoicing, electronic ordering and electronic payment out of the BT-107 (Techniques) codes and rather implement them as separate BTs in BG-705 (Other Requirements and Terms). The main reason is that while techniques generally concern the structure of the whole procedures (e.g. framework agreement), the three items above are only about the post-award phase of procurement. Furthermore, it could be argued that techniques are listed exhaustively in the directives.
