### ISSUE TITLE
BT-707 (Documents Restricted Justification); DataType; Proposal of a codelist "communication-justification"

### ISSUE THREAD

**Issue by paulakeen** [eForms/eForms#290]
We propose that eForms uses the code list, prepared by OP, "communication-justification", which values are:

•	Tools, devices, or file formats not generally available
•	Intellectual property right issues
•	Buyer would need specialised office equipment
•	Inclusion of a physical model
•	Protection of particularly sensitive information

Similar to #291

**Comment by JachymHercher** [comment]
We agree, this is already the case.
