### ISSUE TITLE
BT-19 (Submission Nonelectronic Justification); DataType; Proposal of a code list "communication-justification"

### ISSUE THREAD

**Issue by paulakeen** [eForms/eForms#291]
We propose that eForms uses the code list, prepared by OP, "communication-justification", which values are:

•	Tools, devices, or file formats not generally available
•	Intellectual property right issues
•	Buyer would need specialised office equipment
•	Inclusion of a physical model
•	Protection of particularly sensitive information

Similar to #290

**Comment by JachymHercher** [comment]
We agree, this is already the case.
