### ISSUE TITLE
BT-140 (Change Reason Code); DataType; Proposal of the codelist "Notice-corrigendum-justification"

### ISSUE THREAD

**Issue by paulakeen** [eForms/eForms#292]
We propose that eForms uses the code list, prepared by OP, "Notice-corrigendum-justification", which values are:

•	Correction of one or more mistakes
•	Updated or additional information
•	Correction of a publication error
•	The original notice is cancelled
•	The buyer intends to cancel the original notice
•	Publication of information which was originally postponed for reasons of law enforcement, commercial interests of an economic operator, fair competition or other public interest

**Comment by jpmckinney** [comment]
#247 and #273 suggest improvements to this codelist (including improvements compared to the OP list above).

**Comment by SellittoGiampaolo** [comment]
when the CA issues a corrigendum, also the terms to submit an offer should be changed, giving additional time to formulate an offer ... how do we manage the modification of the submisison deadline when a corrigendum is published?

**Comment by JachymHercher** [comment]
@paulakeen - indeed, this was the codelist published for the consultation, but some changes are now being discussed. I would suggest continuing the discussion in #247 and #273. 

@SellittoGiampaolo The corrigendum will allow changing any data in the notice, including the submission deadline. Furthermore, there should also be business rules which ensure that, for example, if the tender submission deadline is changed, it does not get moved "after" tender opening deadline or the date implied by tender validity.
