### ISSUE TITLE
BT-75 (Guarantee Required Description); Description; ePO alignment and definition

### ISSUE THREAD

**Issue by paulakeen** [eForms/eForms#293]
Following eForms, in ePO we discussed the eForms BT-75 Guarantee Required Description, the guarantee required indication was moved from lot to submission terms and a property Guarantee Descripton was added.  

The definition of guarantee was updated as follows: 

"Financial modality  and request for commitment to be used in case of default examples were given in the additional information".  The definition is slightly more generic than eForms so as to allow for reusability.

**Comment by JachymHercher** [comment]
In eForms, BT-751 (Guarantee Required) and BT-75 (Guarantee Required Description) are in BG-705 (Other Requirements). However, putting them into BG-102 (Submission Terms) is indeed better. We will put them there, next to the related BT-98 (Tender Validity Deadline). 

Concerning the definition, I'm not sure I understand it. [Modality](https://dictionary.cambridge.org/dictionary/english/modality) seems very broad, I'm not sure what "request for commitment" means in this context - isn't that (Commission?) jargon? Does it apply to companies? 

(The definition ends with "default", right?)

**Comment by JachymHercher** [comment]
Based on off-github comments from Lithuania, we will suggest changing the eForms definition to the text below. The main point of the change is that the guarantee is not necessarily a payment, but can also be a document from a financi

> The description of the financial guarantee _required from_ the tenderer when submitting a tender. The guarantee can take the form of, _for example, a payment to the buyer or a document from a bank_. Typically, the guarantee would be _forfeit_ when a tenderer has won the contract but then refused to sign it.
