### ISSUE TITLE
BT-539 (Award Criterion Type); DataType; Proposal of the code list "evaluation-dimension"

### ISSUE THREAD

**Issue by paulakeen** [eForms/eForms#297]
Following discussions in ePO, the evaluation-dimension was modelled in the Ontology. The eForms BT "Award Criterion type" would not fit with the ePO modelling as award criteria are already modelled in the same way as exclusion grounds, selection criteria and participation criteria.  

The evaluation dimension is composed of several award criteria of an individual criterion type ie quality, price cost. The following code list is proposed for the BT "Award Criterion Type":

1. Quality
2. Cost
3. Price

**Comment by JachymHercher** [comment]
We agree, that is indeed what is already in the proposal.
