### ISSUE TITLE
BT-65 (Subcontracting Requirements); Any; This cannot be a code

### ISSUE THREAD

**Issue by paulakeen** [eForms/eForms#298]
In ePO there was a long discussion about the eForms BT-65 which, in eForms, is shown to be a code list.  

The group found it difficult to justify as a code list as it covered concepts coming from different origins, i.e. during the tendering procedure or during the execution of contract like is not being compared with like.  

The different values foreseen were:

1. The tenderer has to indicate in the tender any share of the contract it may intend to   subcontract to third parties and any proposed subcontractor, as well as the subject-matter of the subcontracts for which they are proposed.
2. The tenderer has to indicate any change occurring at the level of subcontractors during   the execution of the contract. 
3. The   contracting authority/entity may oblige the successful tenderer to award all or certain subcontracts through the procedure set out in Title III of   Directive 2009/81/EC. 
4. The successful   tenderer is obliged to specify which part or parts of the contract it intends   to subcontract beyond the required percentage and to indicate the   subcontractors already identified.
5. No   subcontracting requirements

The solution found by the group was to provide separate indicators for the different terms.  A   "Subcontracting Terms" class (equivalent to eForms BG) was created and linked to the class "Submission Terms" and "Contract   Terms".  

The "Subcontracting Terms" class provides for the maximum and   minimum amounts of subcontracting and whether the subcontractors need to be listed it not and provides.  A "subcontracting restriction code" has also been included to cover Title III of Directive 2009/81/EC.

**Comment by JachymHercher** [comment]
This codelist, which copies fields in II.1.7) from the current defence contract notice and closely follows Art. 21 of Directive 2009/81/EC, is indeed quite large and diverse. 

We understand the approach you propose. For the ontology, which carefully describes the relationships between different concepts, splitting the codelist is a good appraoch. On the other hand, if we understood correctly, nothing "structural" has changes compared to the eForms approach (e.g. the information can still be specified at lot level), so the modelling in the current eForms and in the ontology is perfectly mappable.

If that is correct, we would suggest keeping the eForms the way they are. Semantically, we would argue that this information is "related enough" to be within one BT. This view is supported by all the codes coming from the same article in the directive. From a modelling point of view, we try to stick with codelists wherever possible, as it makes things shorter, easier to read and more flexible.

**Comment by paulakeen** [comment]
As @JachymHercher says, the fact that the eForms codes are mappable to the Ontology codes split in different classes is sufficient to ensure the alignment, which fortunately in this is case would "bijective" (meaning 100% aligned from ePO to eForms and vice-versa). 

In which case we should close this issue.

**Comment by paulakeen** [comment]
On second thought, and after discussions on this very specific subjects in ePO, I would like to present the business-wise reasons for the modelling provided by the ePO that would explain why the current solution in eForms will not work:

**I. Code "1. The tenderer has to indicate in the tender any share of the contract it may intend to subcontract to third parties and any proposed subcontractor, as well as the subject-matter of the subcontracts for which they are proposed."**

The **_first code_** mixes up three different concepts:

I.1- The indication of whether the tenderer intends to subcontract, which we solve with an indicator in our class Subcontract Terms;
I.2- The requirement that it has to list all subcontractors, which we solve in the code list "subcontracting-requirement" via the "Subcontract Terms" class; and
I.3- The subject-matters of the subcontract, which we solve with a Description in the "Subcontract Terms";

These three concepts need to be linked also to the Submission Terms, in ePO we have this solve through a property "has Subcontract Terms", which in eForms could be solved by putting the required subcontract terms within BG-102 "Submission Terms".

**II. Code "2. The tenderer has to indicate any change occurring at the level of subcontractors during the execution of the contract.**

In this case the actor is no longer the "tenderer", but the "contractor" and is therefore linked in the ePO via the "Contract Terms" (which is linked to the "Subcontract Terms").  In eForms this could be solved by putting the required "Subcontract Terms" within BG-711 "Contract Terms".

**III. Code "3. The contracting authority/entity may oblige the successful tenderer to award all or certain subcontracts through the procedure set out in Title III of Directive 2009/81/EC."**

This seems to happen at "execution time", please correct me if I am wrong. Therefore the "subcontracting-restriction" code is to be linked to "Contract Terms" via "Subcontracting Terms". In eForms this could be solved by putting the required "Subcontract Terms" within BG-711 "Contract Terms".

**IV.Code 4: "The successful tenderer is obliged to specify which part or parts of the contract it intends to subcontract beyond the required percentage and to indicate the subcontractors already identified."**

This seems as it could happen just before signing the contract. In ePO we think it is solved because the  "Contract Terms" "includes Subcontract Terms" which has "subcontracting-requirements" code "List of subcontractors involved. Likewise, in eForms this would go to the BG-711 "Contract Terms" using the ePo "subcontracting-requirement" code list.

It is felt that the syntagm "required percentage" in the description of the code is covered by the "BT-64 Subcontracting Obligation Minimum" and "BT-729 Subcontracting Obligation Maximum" BTs (under BG-705) and then they should also be integrated in BG-711 "Contract Terms".

**V. "Code 5: No subcontracting requirements"

This is not needed: if there are no requirements then no instances of the classes and associated codes would occur. What would be the need of having this in eForms?

Please consider reviewing the treatment of all subcontracting terms (currently under BG-705) and redistributing them in BG-711 "Contract Terms" and in BG-102 "Submission Terms" in alignement with all the comments above.

**Comment by JachymHercher** [comment]
@paulakeen thank you for your analysis. Based on the above, and some more reading of Art. 21 as well as discussions with colleagues responsible for defence, we would suggest the following approach. 

1) Add a new BT-651 (Subcontracting Tender Indication) to BG-102 (Submission Terms). Description "The  information about subcontracting that must be indicated in the tender."  It should be a code with the following values: 
    - The share of the contract that the tenderer intends to subcontract. 
    - The proposed subcontractor(s) necessary to fulfill the obligation to subcontract a minimum percentage of the contract.
    - The proposed subcontractor(s) above any obligation to subcontract a minimum percentage of the contract. 
    - The subject-matter of the subcontract(s) necessary to fulfill the obligation to subcontract a minimum percentage of the contract.
    - The subject-matter of the subcontract(s) above any obligation to subcontract a minimum percentage of the contract. 
    - None.

2) In BT-65, change "requirement" to "obligation" and move it, together with BT-64 (Subcontracting Obligation Minimum) and BT-729 (Subcontracting Obligation Maximum) to BG-711 (Contract Terms). This should contain the following values (closely based on the current ones):  
    - The ~tenderer has to~ _contractor must_ indicate any change ~occurring at the level~ of subcontractors during the execution of the contract.
    - The ~contracting authority/entity~ _buyer_ may oblige the ~successful tenderer~ _contractor_ to award all or certain subcontract(s) through the procedure set out in Title III of Directive 2009/81/EC.
    - New: The contractor must subcontract a minimum percentage of the contract using the procedure set out in Title III of Directive 2009/81/EC. (The code was supposed to be added based on https://github.com/eForms/eForms/issues/117#issuecomment-426327361, but it seems we forgot to do it.)
    - ~The ~successful tenderer~ ~is obliged to~ specify which part or parts of the contract it intends to subcontract beyond the required percentage and to indicate the subcontractors already identified.~ (This can be removed because it also refers to the information to be submitted in the tender, see "also" in subparagraph 5 of Art. 21(4), and so it is now covered by BT-651)
    - None.

(Concerning the purpose of the last code, this is a part of the general approach in eForms, where we try to explicitly differentiate between, for example, "I forgot to fill this in" and "there were no requirements".)

3) Business rules should be added. 
    - If "The contractor must subcontract a certain minimum percentage of the contract using the procedure set out in Title III of Directive 2009/81/EC." is selected in BT-65, then BT-64 (Subcontracting Obligation Minimum) and BT-729 (Subcontracting Obligation Maximum) should be mandatory. (+ Another rule that, on the contrary, if the code was not selected, the values should not exist.) 
    - If "The contractor must subcontract..." is selected in BT-64, then "The share of the contract that the tenderer intends to subcontract." and "The subject-matter of the subcontracts necessary to fulfill the obligation to subcontract a minimum percentage of the contract." must be selected in BT-641 (see 2009/81/EC Art. 21(4) subpara. 5). 

(For the record: we've checked the use of these fields in the current forms and they seem to be quite used, with each one having had been used in between 700 - 4400 notices.)
