### ISSUE TITLE
BT-63 (Variants); Any; Reusability of the "permission" the code list

### ISSUE THREAD

**Issue by paulakeen** [eForms/eForms#299]
In ePO, when discussing the variants it was decided that the code list for the BT "Variants", containing the values:
1. Authorised, 
2. Required,
3. Not allowed  

should be called "Permission", so that it can be used also for the code list required for electronic submission the value of the codes would therefore be Authorised, Required and Not allowed to be in line with the terminology of variants in the Directive.

Equal to #300

**Comment by jpmckinney** [comment]
Would Required, Allowed, Not allowed, be clearer? (Or Required, Authorized, Not authorized) I'm not sure why "authorized" and (not) "allowed" are both used. Using one term consistently would be clearer.

**Comment by SellittoGiampaolo** [comment]
I agree with the use of a codelist, but the codelist should include further codes, expecially in the casethe use of the same codelist is foreseen in other contexts.

**Comment by paulakeen** [comment]
Please feel free to propose the missing codes @SellittoGiampaolo!

**Comment by muricna** [comment]
The authorised was to be in line with Article 45 of 2014/24/EU when the code list is used for variants "Contracting authorities may authorise or require tenderers to submit variants."

**Comment by SellittoGiampaolo** [comment]
OK, 
my concern was about the 2nd comma in Article 45, but after some discussion her, it seem that the values Authorised, Required, Not allowed can cover all of the needs regarding the possibility to propose vaiants, leaving further specifications to other sections.

The 2nd comma in Article 45 states:
2. Contracting authorities authorising or requiring variants shall state in the procurement documents the minimum requirements to be met by the variants and any specific requirements for their presentation, in particular whether variants may be submitted only where a tender, which is not a variant, has also been submitted. They shall also ensure that the chosen award criteria can be applied to variants meeting those minimum requirements as well as to conforming tenders which are not variants.
3.   Only variants meeting the minimum requirements laid down by the contracting authorities shall be taken into consideration.

**Comment by jpmckinney** [comment]
@muricna Should "Not allowed" be changed to "Not authorized" in that case?

**Comment by JachymHercher** [comment]
I would also be in favor of "required", "allowed", "not allowed". I would argue that "allowed" is better than "authorized" because it is more common, it's not jargon.

Using the permissions codelist for BT-63 sounds fine. However, the description of the BT needs to change. We would suggest something like:

> Whether tenderers are required, allowed or ~forbidden~ _not allowed_ to submit tenders which fulfil the buyer's needs differently than as proposed in the procurement documents. Further conditions for submitting variant tenders are in the procurement documents.
