### ISSUE TITLE
BG-703 (Organisation); all; grey shading

### ISSUE THREAD

**Issue by MaKilbane** [eForms/eForms#3]
What is the significance of the grey shading in some cells - for example BG-703 has a mandatory legal status 'M'

![capture](https://user-images.githubusercontent.com/22935453/41281992-c3cae37e-6e2a-11e8-9894-f26d984cc1be.PNG)

**Comment by JachymHercher** [comment]
It's a visual way of distinguishing BGs from BTs, intended to make things easier to read. All BG rows are shaded in grey.
