### ISSUE TITLE
BT-111: Framework Buyer Categories: meaning of "categories of buyers"

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#30]
What does "categories of buyers" mean here? Is there really a need to mention the name of FA participants in the CN or CAN... often this is a very long list? How does this effect the buyer identification number?

**Comment by JachymHercher** [comment]
According to the procurement directives, all buyers concluding a framework agreement must be clearly identified. This indication can either be done organisation by organisation using BG-703 (Organisation) or, on a more general basis, in this BT by describing the "buyer category". An example of a buyer category is for example, "all municipalities in the Tuscany region". 

The idea is exactly to avoid the need to have a long list. No names and identifiers are given in such a case. (They would be included, however, if contracts within framework agreements are published.)

For more information, please see 2014/24/EU Art. 33(2) second subparagraph.
