### ISSUE TITLE
BT-111 (Buyer Framework Categories); Name; Naming improvement 

### ISSUE THREAD

**Issue by paulakeen** [eForms/eForms#301]
In ePO, for BT-111 "Buyer Framework Categories", it was decided that to use the term "Buyer Coverage". The definition in ePO, based on the eForms' one, reads as follows: 

"Buyers that can use the Framework Agreement not mentioned by name."

Additional Information: e.g. "all hospitals in the Tuscany region"

**Comment by JachymHercher** [comment]
I'm not sure whether this doesn't make things more confusing. With this definition, how should the user decide whether to include information about the buyer using the organisation section or BT-111? Under the original description, it seems clearer that in one case you list individual buyers, in the other case categories of buyers. 

Also, please note that using the word "category" sticks with the terminology of the directives, in particular Rec. 60 of Directive 2014/24/EU.
