### ISSUE TITLE
BG-6 (Procedure); Lots Min Awarded; Obligation to bid on all lots (revisited)

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#303]
In #80 we already shortly discussed the subject of an “Obligation to bid on all lots”. Since we could not answer on time (and the ticket contains far too many topics), the discussion was cut short.

Relevant comments are the inquiry https://github.com/eForms/eForms/issues/80#issue-339465208 and @JachymHercher's answer no 10 in https://github.com/eForms/eForms/issues/80#issuecomment-403874012, I quote:

(me)
> [...] the following list of German national procurement Business Terms/Groups... would be needed to document national procurement by means of eForms notices: [...] obligation to bid on all lots

(Jáchym)
> Initially we planned to include it, but then we were not sure on how this exactly works and when it is useful. Essentially, it forces tenderers to bid even for lots they would not be interested in. However, how can the buyer avoid that tenderers just submit nonsensically high bids for lots they are not interested in? Also, if the aim is to be able to have the same winner for all contracts, isn't this business need covered by BG-330 (Group Award)?

The use case is as follows: Germany has both strict laws and regulations for public construction projects that force the buyers to break down construction works into small lots, often each craft separately, in order to facilitate SME works and deliveries. These works are thus portioned in business lots which often themselves become own tendering procedures (up to some 30), each to be executed in direct interdependence and according to a predefined construction schedule which often means almost right on time, i.e., operations usually start right after the award. In effect, although the procedures and lots are technically independent, strong dependencies exist and must be managed.

This leads to a situation where tendering procedures with lots that attract little or no buyer attention often lead to standstills of whole construction sites. The buyers therefore need instruments to lead tenderers to offers also for the less attractive lots, either by instruments currently operated on below-threshold construction notices “The bidder is obliged to bid on all lots”, or, perhaps more flexible, to add rules such as “if a bid is places on lot 1, it also must include lot 4”.

@JachymHercher
1. In case just submit nonsensically high bids for lots they are not interested in, in the worst case such bids are awarded if every tenderer acts this way. 
2. Perhaps we do not really understand the sense of Group Awards, but as I understand it, there is nothing mandatory to them and as long as lots are separate, all lots can in principle be subject to sole bids, cannot they?

**Comment by JachymHercher** [comment]
1. Ah, right.  
2. Yes, BG-330 does not help with the use case you mention. 

There are several possible implementations: 
1. At the end of BG-6, add an indicator along the lines of "The bidder is obliged to bid on all lots”. 
2. Adding a BT analogous to BT-31 (Lots Max Allowed). This could be called Lots Min Required and have a description of "Minimum number of lots for which one tenderer must submit tenders." It can be equivalent to 1., but could also be used more flexibly. 
3. Adding a BG analogous to BG-330, which would allow defining groups of lots and then require submitting tenders for all lots in the group. It can be equivalent to 1, but could also be used more flexibly. 

What do you think would work the best?

**Comment by tinne** [comment]
All three options are feasible. My construction colleagues would prefer implementation 1, as it is well-known and easy to apply.

Regarding implementation 2, this might better align with BT-31 and BT-33. We did not find a reasonable application for bids on “at least 2, ..., _n_-1” lots.

Regarding implementation 3, the only additional case considered useful was like ”every bid must include lot 1“, for which it was remarked that an implementation in lot number sets could row rapidly (with square pace) with the number of lots. As there is no urgent use, this implementation maybe should only be implemented if there are other votes in favour of it.

**Comment by JachymHercher** [comment]
@tinne Then unless additional requirements come, we will follow option 1, i.e. something like


Lot All Required | Indicator | No | The tenderer must submit tenders   for all lots.
-- | -- | -- | --

However, a follow-up question about 1. Another easy way to avoid this obligation would be to submit inadmissible tenders for the lots I do not want. How do German authorities deal with that? Does the obligation to submit tenders for all lots imply that if a tender gets excluded for one lot, then it will be excluded from the whole procedure?

**Comment by tinne** [comment]
This issue got lost, sorry for the delay.

The authorities would not exclude inadmissible tenders from all other lots. These cases are expected to be singular, one would not expect a majority of bidders to make their offers for unpopular lots unusable in this way.

If however one would find such cases accumulate in a certain craft and a tendency  to deliberate distortion of competition would manifest, this would possibly result in a reworked lot tailoring for the future.

**Comment by JachymHercher** [comment]
@tinne Thank you for the explanation, for the purpose of the field this is enough. In practice, there still seems to be a bit of a "loophole", but if it works for now, it works for now.
