### ISSUE TITLE
BT-730 (Subcontracting Known); Description; What if only description known?

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#305]
The description to BT-730 says,
> The buyer knows at least the estimated value and description of the part of the contract that the contractor will subcontract to third parties.

As this has direct effect on BT-553 and BT-555 (via BR-285 and BR-388), this formulation seems to be questionable.

With a lot of construction procurements, buyers know exactly which trades will be subcontracted (e.g. mixing and bringing in concrete in contrast to applying armouring), but not the actual value of the subcontracted values. In order to fulfil the business needs, they would thus need to state Subcontracting Known "No", as they do not know **both** value and description of this subset, and then give a Subcontraction Description describing the works?

**Comment by JachymHercher** [comment]
This is at the moment that the tender has been submitted, finalized, etc. If the tender is known and the trades are known, are you sure that at least an "estimated" value/proportion is known? I would think that an estimate (5%; 30%; 80%) should always already be known?

**Comment by tinne** [comment]
As I was told from the practise, only a rough estimate could be derived. In the example, relevant guesses would have to be made at least on steel, gravel and sand prices, subcontractor logistics costs, etc.

The question was therefore whether it would make sense to split BT-730 into “the buyer knows the estimated value” and “the buyer can describe the subcontracted parts“.

**Comment by JachymHercher** [comment]
1) There's a typo in the description of BT-730. Corresponding to the cardinalities and BRs, it should have said "value and proportion", not "value and description". So you are definitely right. 
2) Some comments on https://ec.europa.eu/info/law/better-regulation/initiatives/ares-2019-797630_en also make the same point. In particular, that a contract could specify "what" is to be subcontracted, but would not require disclosing how much it cost. So, again, description and cost should definitely be decoupled. 

    However, is there a situation where "proportion" could have a numerical value and be known, while "value" would not? Could "proportion" be some kind of buyer's estimate of the "proportion of the work"? On one hand, it sounds intuitive, but on the other, I'm essentially wondering what unit the "proportion" could represent, if not money? (How else to represent something that is a combination of material, people, machinery use, etc.)

**Comment by tinne** [comment]
In theory, no. For all practical purposes, sure. Given a large framework agreement with two a three contracts granted within. Now, the total value gives only some upper bound on what may be done including all possible extensions, etc. Obviously, the buyer chooses a total that fits budget but not necessarily the amount of work readily available at the time of planning.

I have seen situations where the buyer for competition reasons committed itself to never award a contract within the framework to that contractor who would have extended its share too far over a certain proportion of the total budget spend. Thus, a relative boundary could be established while the absolute boundary was a movable target of the execution period of the framework. Guess the same construction would work with subcontracting similarly.

**Comment by JachymHercher** [comment]
We're not 100% sure that this is the best solution, but for the next version, we will propose separate indicators BT-730 (Subcontracting Value Known) and BT-731 (Subcontracting Percentage Known). 

BR-285 and BR-388 will be updated accordingly.

**Comment by tinne** [comment]
Is't this the equivalent of making Subcontracting Value and Subcontracting Percentage optional and declaring in the description “must only be omitted if unknown“?

The question remains whether if both are unknown, a Subcontracting Description should be given if the buyer known that any amount of subcontracting will take place.

**Comment by JachymHercher** [comment]
One of the goals of eForms is to have, as far as useful, things which are legally and technically mandatory aligned. Also, "unknown" is useful information (and something else than "forgot to fill in"), so it is worth differentiating them. 

BT-554 (Subcontracting Description) is a text field and it is never a legal obligations (just the value and proportion are), so we can simply leave it optional.

**Comment by JachymHercher** [comment]
In the discussion above, we have omitted the distinction between "subcontracting not known" and "there is no subcontracting". 

To remedy this, we will suggest to add the following term into BG-180 (Subcontracting):

BT-773 | Subcontracting | Indicator | No | At least a part of the contract   will be subcontracted.
-- | -- | -- | -- | --
