### ISSUE TITLE
BT-753 (Selection Criterion Second Stage Number Meaning); Code; Ranges

### ISSUE THREAD

**Issue by paulakeen** [eForms/eForms#309]
If a range needs to be used, and codes like Weight (percentage, middle of a range), 
Weight (decimal, middle of a range), Weight (points, middle of a range), etc... are applied to that range, then the code would not be referring to one number, but two numbers....or am I missing something you already solved in eForms?

We need to know your solution so we can also correct the ePO conceptual data model.

Thanks.

**Comment by JachymHercher** [comment]
The "middle of a range" means that the end-points of the intervall would not be modelled in eForms, only the center would. 

For example, if a weight given in the procurement documents would be 10-20%, then the information in the notice would be "middle of a range" = 15%. The same information would be given if the range was 0-30%.  

This is inaccurate, but given the rarity and obscurity of using ranges for award criteria, we believe it is enough. Please note that ranges only exist in contract notices (where information about award criteria is anyway voluntary), not in contract award notices.
