### ISSUE TITLE
Will the eForms be specified by an XML Schema?

### ISSUE THREAD

**Issue by sorliden** [eForms/eForms#310]
Hi eForms team!

Will the new eForms be specified by an XML Schema or are you looking at another specification technology?

Best regards
  Mårten

**Comment by JachymHercher** [comment]
Hello, we apologize for the slow reply. 

As mentioned by @YvesJo in https://github.com/eForms/eForms/issues/206#issuecomment-444168973, the main candidate for the specification will be an XML Schema using the UBL syntax. The same solution is also used in the other two Commission "standards" in the area of public procurement - https://github.com/ESPD/ESPD-EDM and eInvoicing. 

In https://github.com/eForms/eForms/issues/260, there is also a discussion on how the JSON-based Open Contracting Data Standard could be used.
