### ISSUE TITLE
Green Social and Strategic Procurement BT-774 BT-775 BT-776

### ISSUE THREAD

**Issue by SellittoGiampaolo** [eForms/eForms#311]
The focus on Strategic Procurement is bound to have an high impact on Procurement in the next years, also in consideration of the SGI objectives.
From this point of view,  thefollowing code for lots: 
BT-774 : Green Procurement 
BT 775 : Social Procurement
BT 776 : Innovative Procurement 
need further elaboration  to catch the inherent diversity both in content and usage during the different procurement phases

**Comment by JachymHercher** [comment]
We have updated the codelists based on feedback from Member States, please see http://ec.europa.eu/transparency/regcomitology/index.cfm?do=search.dossierdetail&Dos_ID=17796&dos_year=2019&dc_id=. We are also expecting further comments as part of theMember States' official opinion.
