### ISSUE TITLE
BT-759 (Received Submissions Count).BT-760 (Received Submissions Type); Description:Number and type of tenders received

### ISSUE THREAD

**Issue by jadelanava** [eForms/eForms#312]
We have a question about the calculation of the number of offers received in a tender and its disaggregation between offers submitted by SMEs and by non-SMEs. 

The purpose is to analyze the participation of SMEs in public procurement as well as the number of tenders that have received a single offer.

1)	Is the total number of offers submitted included in the business term BT 759 (Received Submissions Count)?

2)	We quite not understand the operation of the Business term BT 760 (Received Submissions Type). The answer to this Business Term is in code mode, and within it the options are the following:

- Requests to participate
- Tenders
- Tenders from micro, small or medium tenderers
- Tenders from from micro tenderers
- Tenders from small tenderers
- Tenders from medium tenderers
- Tenders from tenderers registered in other European Economic   Area countries than the country of the buyer
- Tenders from tenders registered in countries outside of the   European Economic Area
- Tenders verified and inadmissible
- Tenders verified and inadmissible because of an abnormally low   price or cost
- Tenders for which it has not been verified if they are   admissible or inadmissible
- Tenders submitted electronically

How can the contracting authority indicate the number of offers received by SMEs?

This data was covered in other versions of the spreadsheet "e Forms ACPC Annex Table" by the BT 148 (Received Tenders SME) and in the latest version it does not appear.

In the document "e Forms ACPC explanatory note" is proposed as suggested by the Commission and Mandatory.

**Comment by tinne** [comment]
Does checking #227 help with this issue?

**Comment by JachymHercher** [comment]
1. Yes

2. There will be multiple copies of BG-712 (Received Submissions). Each copy of the BG will have a different value of BT-760 (Received Submission Type). The result is essentially the same as if these were individual fields, but is shorter, and so a better way to model this information.

Indeed, this information is not listed correctly in the Annex of the explanatory note. It should be moved from table Policy Fields I (general) to Policy FIelds III (codelists).
