### ISSUE TITLE
BG-125 Previous Planning

### ISSUE THREAD

**Issue by jseguraf** [eForms/eForms#318]
This Business Group is optional in the Planning phase and this is not correct since the PIN planning does not know another previous planning.

**Comment by JachymHercher** [comment]
During the eForms discussions, we have been informed that in some countries, there could be several PINs at the beginning of the procedure. In particular, this could happen when PINs are used to inform about a preliminary market consultation (possibly in multiple rounds) and then as an "actual" PIN, to inform about a planned procurement. 

In the future, DG GROW is planning to provide specific "preliminary market information notice", which can be filled in a form similar to an eForms' planning form - see https://github.com/eForms/eForms/issues/81#issuecomment-509251440.
