### ISSUE TITLE
BT-161: Notice Value: how about lots

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#32]
This may be difficult to interpret as Lot values are under different BT number: is BT-161 for contracts and BT-118 for Framework agreements? How about DPS?

**Comment by JachymHercher** [comment]
Yes, BT-161 (Notice Value) is about the value of signed contracts; BT-118 (Notice Maximum Value) is about the maximum value of a framework agreement, i.e. the money that _could_ be spent in the framework agreement.  

DPS does not have a maximum value, only the value of specific contracts, so the values of contracts resulting from a DPS would go into BT-161. 

Concerning lots, the BT-161 is essentially a sum of the values of all the contracts (covering all the lots) in the notice.

**Comment by paulakeen** [comment]
Does BT-161 include the values of the Lots covered by a Framework Agreement?

**Comment by JachymHercher** [comment]
BT-161 includes the _values_ of _contracts_ awarded within a notice, regardless of whether they were awarded within a (lot falling under a) framework agreement or not. BT-161 does not cover the _maximum values_ or _estimated values_ of _framework agreements_ that were announced in a notice. 

(The maximum and estimated values of framework agreements announced in a notice are covered by BT-118.)
