### ISSUE TITLE
BG-706 (Techniques); May differ per lot?

### ISSUE THREAD

**Issue by jpmckinney** [eForms/eForms#321]
The current standard procurement forms specify techniques (FA, DPS, electronic auction), in a Section IV: Procedure, which describes the entire procurement, not a lot. In eForms, this information is instead per lot. Can you confirm that such techniques can differ per lot?

**Comment by JachymHercher** [comment]
We confirm. (As always, Member States are free to implement it as they want in their systems. However, by the Directives, there could be a lot with a framework and a lot without a framework in one procedure. Furthermore, there are real-world scenarios where this would be useful, e.g. one lot on "Create a methodology for evaluating cars" and one lot for "Evaluate car X, which just came out".

**Comment by jpmckinney** [comment]
Thank you!
