### ISSUE TITLE
BG-706 (Techniques); Description; Mentions electronic ordering

### ISSUE THREAD

**Issue by jpmckinney** [eForms/eForms#322]
BT-92 (Electronic Ordering) is under BG-711 (Contract Terms) not under BG-706.

**Comment by JachymHercher** [comment]
Yes (see https://github.com/eForms/eForms/issues/29#issuecomment-439351537). This also aligns eForms with the eProcurement ontology.

**Comment by jpmckinney** [comment]
Sorry, my issue was unclear. The Description for BG-706 (Techniques) mentions electronic ordering, despite the linked change: "Information about the use of sets of techniques such as framework agreements without reopening of competition, framework agreements with reopening of competition, dynamic purchasing systems, electronic auctions **and electronic ordering**. This information may differ per lot. In case of a prior information notice or a periodic indicative notice used only for information, this information may differ per part of the notice that may later become a lot or a self-standing procedure."

**Comment by JachymHercher** [comment]
Ah, well spotted, thank you.
