### ISSUE TITLE
BG-704 Why "reward" if "prize" seems to be used everywhere

### ISSUE THREAD

**Issue by ColinMaudry** [eForms/eForms#325]
Hi there,

I wonder why this BG is titled "*Reward* and Jury" while both the sub-terms and the legislation only mention "prizes" and never mentions "rewards".

Isn't "Prizes and Jury" more in line? I'm afraid using two synonyms could make some people think rewards and prizes are different things.

Thanks.

**Comment by JachymHercher** [comment]
There is indeed a difference - prize is just a type of a reward. There can be two types of rewards in a design contest:
- Prizes (BG-44)
- Receiving a follow-up contract (BT-41).

**Comment by ColinMaudry** [comment]
I guess they are not mutually exclusive, right?

**Comment by JachymHercher** [comment]
Yep.

**Comment by ColinMaudry** [comment]
Merci @JachymHercher  !
