### ISSUE TITLE
BG-101 (Procurement Documents) / BG-705 (Other Requirements); ALL; Protecting Confidential Information

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#327]
Recent changes in German below-threshold construction notice jurisdiction (VOB/A 2019) demand that buyers are allowed to take measures to take measures to protect information given in the restricted part of the procurement documents.

It allows them to “take measures to protect confidentiality of the information. The contracting authority may in particular on the submission of a non-disclosure agreement”, and requires “The measures shall be specified in the contract notice.”

Our construction notice specialists thus added the topic to the VOB forms (121 and 122) as follows:

#### “Measures to protect confidential information
- [ ] Submission of confidentiality agreement
- [ ] Other measure (provide description)”

Any ideas how to represent this in eForms? Most obviously BT-14 Documents Restricted must be true, but the nearest approximation I see is to have BT-578 Security Clearance true as well and give some sort of standard text for BT-732 Security Clearance Description. Can this be improved upon?

**Comment by JachymHercher** [comment]
eForms have been adopted this year, so nothing to be added until a future revision. 

Concerning using the eForms as they are, BT-578 and BT-732 sound good. BT-707 (Documents Restricted Justification) could also be used; so could simply BT-300 (Additional Information).

**Comment by tinne** [comment]
Last time I was involved, a permanent change process was being considered. So if you don't mind or recommend another tool, why not use this one (you could even add a Milestone for future consideration).
