### ISSUE TITLE
Usage of the Procedure and Lot in the Planning stage (REGULATION (EU) 2019/1780)

### ISSUE THREAD

**Issue by jseguraf** [eForms/eForms#328]
During the latest WGM of ePO, we were mapping the PINs of the Planning stage against to the ePO concepts. For the mapping we used the new regulation. However, some questions and doubts came up from a first analysis of the Planning stage:

1. According to the Purpose definition: “Information about the purpose. This information must be given for the whole procurement procedure and, if they exist, also per lot. In case of a prior information notice used only for information, this information may differ per part of the notice that may later become a lot or a self-standing procedure”, should purpose not foresee planned procurement as well as procurement and lots?  

2. Are lots already know at the planning stage if not then why are there optional fields in the planning stage? For example:

![image](https://user-images.githubusercontent.com/33545990/68933010-10679700-0794-11ea-8a3b-fa0b0d79c1b8.png)

**Comment by ec-mcs** [comment]
I do not fully understand the question.
The PIN is usually used to tease a procurement procedure and to shorten deadlines. Often at this time, not all information is available and as such I assume that clear information about lots are not available.

**Comment by JachymHercher** [comment]
@jseguraf 
1. The planning form is used to publish the prior information notice, i.e. the following text relates to the planning phase:  "In case of a prior information notice used only for information, this information may differ per part of the notice that may later become a lot or a self-standing procedure.”
2. See previous answer - there are "parts", which may sometimes end up corresponding to "lots", sometimes not. Consequently, some users may want to use fields that would apply to lots. 

(For more information about parts, see e.g. https://github.com/eForms/eForms/issues/269#issuecomment-475561237.)
