### ISSUE TITLE
BT-148 (Received Tenders from SME); Description; Number by company size

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#33]
For this to be usefu,l the question should be on the number of micro, small and medium sized enterprises separately.

**Comment by JachymHercher** [comment]
This is an interesting proposal - which would make the type of information consistent with BT-165 (Winner Size). In some countries, it might be possible to also include this information automatically (e.g. from ESPDs; eSubmission modules and business registries).  

Depending on the interest of other Member States in better information on SME participation and having comparable data across countries, such a split could either be included as a mandatory BT in the eForms or offered as a voluntary extension.

**Comment by bouwesamplonius** [comment]
I think we should really ask ourselves if the contracting authority will be happy with the addition of BT-148. If you want usable, reliable and correct SME information then it is mandatory to connect the tender boards to the local chamber of commerce to get correct information. The chamber of commerce registers the size of the enterprise. In The Netherlands but maybe also elsewhere it is a bit difficult to create such connection.

Without this, i don't think the contracting authorities will put a lot of time in counting the SME's and fill this mandatory filed with a fictional number. I see this happening already with for example the field 'VAL_TOTAL' in the current 2.0.9.S03 version form F03.

**Comment by JachymHercher** [comment]
BT-148 is already in the current forms and is requested by the directives, so not much room for maneuver there. However, further splitting is indeed an open question (personally I'm inclined toward rather putting in the extensions) - thank you for the opinion. 

Connecting with business registries (or at least automatically taking the data from the submitted ESPDs) is indeed the way to go. 

Users putting in fake information can indeed happen. However, the authorities are behaving illegally by doing this and we do believe this trend will go down with more automation, user education and better business rules in both eForms and the implementing systems.

There is a [Commission recommendation](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex:32003H0361), but not all EU countries use it. It is currently being revised.

**Comment by manevmi** [comment]
Contracting authorities will probably put the burden on the tenderers - the latter will need to identify to which category they belong: micro, small, medium, other. If the eSubmission system has a  sort of SME wizard helping the tenderer to identify the correct category, data can be indeed reliable. However, this will increase the burden on tenderers and make submission more lengthy and cumbersome.  Can this be justified by the need to collect statistical data?

In sum, not in favour of splitting. For a tenderer it would be easier to answer whether it is a SME rather than to identify to which category exactly it belongs.

**Comment by JachymHercher** [comment]
Noted. However, please be aware that for submitting the ESPD, tenderers already need to know whether they are an SME (and, in higher versions of the ESPD, which sub-category).

**Comment by bouwesamplonius** [comment]
Agree with @manevmi. If this stays mandatory then we recommend no splitting. It is the least thing that we can do to minimize the workload of contracting authorities.  I agree that connecting to a business register is the way to go, but it sounds easier then done.

**Comment by UHMYND** [comment]
Connecting to business registers seems like the way to go. For statistical purposes we use the organizational identifier of all suppliers to establish company size according to the EU-definition, based on information in national business registries. We add the information to the procurement dataset ourselves, like an "added field". This requires the organizational identifier of the supplier and access to business registries. In my experience the SME-defintion is reasonable but not easy to apply, even with access to all information in a business registry.
