### ISSUE TITLE
BG-320 Tender and BT-3201 Tender Identifier

### ISSUE THREAD

**Issue by jseguraf** [eForms/eForms#330]
In ePO we were analysing the BG-320 and the BT-3201, and how they can be covered in the eProcurement Ontology. During that analysis some doubts raised up: 

- Is the business group referring to any tender or only to the winning tenders? 
- If it refers only to the winning tenders, it does not take into account other information, for example, the lowest and the highest price. 
- There is also a missing relationship between the tender and the winner if it is the winner tender.

**Comment by JachymHercher** [comment]
1. Any tender. If it is a winning tender, then BT-171 (Tender Rank) must be equal to 1. 
2.  Lowest and highest price are lowest and highest price _per lot_. Consequently, this summary information is given per lot in BG-137 (Procedure Lot Result), see  BT-710 (Tender Value Lowest) and BT-711 (Tender Value Highest). 

    (These different fields co-exist because implementers can choose between different ways of providing information about tender value: e.g. for all tenders; only for the winning tender; only for the lowest and highest tender. Out of these options, we would recommend collecting and publishing information about all tenders.) 

3. In eForms, the relationships always go in the opposite direction: from organisation to another section (this design decision resulted from the detailed analysis in https://github.com/eForms/eForms/issues/285). Consequently, the tenderer/winner is linked to BG-320 by putting the Tender Identifier (BT-3201) in BT-13720 (Organisation Notice Section Identifier).

**Comment by tinne** [comment]
1. If there is more than one winning tender, should they all be ranked 1? Especially in the case of a framework agreement a buyer may wish to choose more than one winning tenderer.

In general, would you agree that same numbers are appropriate when tenders rank equally? If yes, would following tender rank numbers be closed up or left in absolute order (e.g. there are two out of four sellers on rank 1, would they be numbered 1, 1, 3, 4 or 1, 1, 2, 3)?

**Comment by tinne** [comment]
To add to the questions for the all tenderer are documented scenario, I am not quite sure how to communicate multiple tenders (for one lot) by the same tenderer. This is what I found in the description of BT-759:

> “Tenders including variants or multiple tenders submitted (for one lot) by the same tenderer should be counted as one tender.”

If I understand this correctly, given that there are valid tenders from tenderers A, B and C, and they rank first (best to worst) tender by A, then tender by C, then B.1, B.2, A.2; this seems to suggest that every tender but the best should be dropped and ignored, so that the result reported is A=1, C=2, B=3.

**Comment by GPsellitto** [comment]
In some MS (e.g. Italy) multiple tenders by the same tenderer are not allowed 
Taken into account that the selection procedure is logically aimed at selecting a tender it should not be a problem to rank Tenders and not Tenderers - the tenderer is only indirectly selected, based on a tender. (from the legal point of view and considering case law, the evaluation regards tenders and it is forbidden to mix characteristics of a tenderer among the factors that are evaluated...
the Characteristics of the tenderer only matter for Exclusion Grounds and for Technical and Financial capability, but these cannot be assigned a quantitative evaluation...)

**Comment by JachymHercher** [comment]
@tinne Yes. Specifically, if the framework agreement (FA) will be with reopening of competition, then all should have 1; if the FA will be a cascade, then the different winners would have ranks 1,2,3, etc. 

> In general, would you agree that same numbers are appropriate when tenders rank equally? If yes, would following tender rank numbers be closed up or left in absolute order (e.g. there are two out of four sellers on rank 1, would they be numbered 1, 1, 3, 4 or 1, 1, 2, 3)?

Good point, to be decided by OP - @yvesjo, @annalisavacca.  

Concerning reporting on multiple tenders, these should be treated exactly the same as tenders from separate tenderers. I.e. the rank would be A(has rank 1), C(2), B1(3), B2(4), B3(5). Similarly, each of them can have their own BT-320 (Tender). The only exception to this rule is for the purpose of the summary statistical field BT-759, where you ignore variant/multiple tenders.
