### ISSUE TITLE
Few minor issues

### ISSUE THREAD

**Issue by JachymHercher** [eForms/eForms#331]
We have received some feedback after the adoption of the eForms act. This issue lists the feedback that could be reflected in a future update of eForms. eForms will eventually be updated in line with the rules and processes described in the eForms Governance document. 

All the issues listed below are minor, none of them require an update as of themselves. 

1. BT-98 (Tender Validity Deadline) can be used more broadly than indicated in the Annex (e.g. for example, in Denmark it is used in the Defence Directive). The field should be added as optional for notices 7 to 22. 
2. BG-44 (Prize) could be used together with Innovation Partnerships and Competitive Dialogues. Consequently, BG-44 (Prize) should be added as optional also for columns 7-14 and 16-22. 

    In the descriptions of BG-44, BT-644 and BT-44, "in a design contest" should be replaced with "in a design contest, innovation partnership or competitive dialogue". 

    Furthermore, in BG-320 (Tender) and BT-171 (Tender Rank), “and innovation partnerships” should be replaced with “, competitive dialogues and innovation partnerships”. 

    (Based on https://github.com/eprocurementontology/eprocurementontology/issues/216#issuecomment-527884785). 
1. In the English language description of BT-263 (Additional Classification Codes), there is a typo: “An additional code from the classification that also characterize!**s**! the purchase.” (The "s" is missing.)
4. In BT-556 (Group Framework Value Lot Identifier) and BT-557 (Group Framework Estimated
Maximum Value Lot Identifier)" “An identifier of” and “Identifiers of lots”, respectively could be replaced by “An identifier of one of several lots within this procedure that form a group.” This is to keep consistency with other descriptions, where repeatable fields are described in the singular.

**Comment by ColinMaudry** [comment]
Thank you very much for you watch :slightly_smiling_face:
