### ISSUE TITLE
BT-191: Country Origin - why ask if optional

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#35]
Why does this have be asked at all if the data is optional? What purpose does this information serve if it's optional?

**Comment by JachymHercher** [comment]
This BT must be included in the standard forms in line with 2014/25/EU Annex XII Point 17. 

The concept of [country of origin](https://en.wikipedia.org/wiki/Country_of_origin) appears in the context of the GPA and the legal obligation probably originated there. Currently, doubts are frequently raised on how realistic it is to track it in a world of globalized value chains. For example, it might be complex to define the country of origin of a car made in country A using components from country B made from sub-components from country C made from materials from country D. Nevertheless, the legal obligation is still there.
