### ISSUE TITLE
BT-1701: Winner Organsiation Reference: consortia & relied upon parties

### ISSUE THREAD

**Issue by rantati7** [eForms/eForms#37]
A very similar situation to consortia is formed when a company submits the bid together with relied upon entities. Do the relied entities need to be listed? It would make sense to list them in the contract or agreement as their role is often cricial for performing the contract. Hence: which entities references would need to be provided here?

**Comment by JachymHercher** [comment]
The annex specifies that reference(s) should be given to organisation(s) that "submitted the winning tender". We take this as being equivalent to the organisation(s) which will be signing the actual contract with the buyer. 

Reliance on the capacities of other entities (in the sense of 2014/24/EU Art. 63) does not, by itself, imply contractual relationship with the buyer. This stems for example from Art. 63(1) subparagraph 3, which mentions that "the contracting authority **may** require that the economic operator and those entities be joint liable for the execution of the contract". In other words a "relied upon" entity might or might not be one of the organisations submitting a bid, depending on other legal (potenetially quite complex) arrangments between the future contractors. As such, we would think it's perhaps less confusing to not mention this topic in the description at all.

Do you find this approach reasonable? 

(@ec-mcs might want to follow this discussion)
