### ISSUE TITLE
BT-501 (Organisation Identifier); Description; Can only some types of identifiers be allowed?

### ISSUE THREAD

**Issue by hutershvili** [eForms/eForms#4]
Can it be further specified that it should be the entity's company registration ID that is provided as the "Organisation Identifier"? 
There may be a number of other IDs that could potentially be filled in this field, such as as a VAT or tax ID which could not be be easily cross-referenced with the company name.

**Comment by JachymHercher** [comment]
It would be useful to have opinions from various EU Member States on this proposal. However, given the huge diversity of approaches to identifiers across the EU, my intuition would be that restricting the types of IDs would not be feasible / useful. For example, in different countries it might be different types of identifiers that may be the most practical or appropriate for the use in public procurement.

Nevertheless, further restrictions on identifiers to be used in public procurement can of course be done at national level.
