### ISSUE TITLE
BT-713 (Buyer reference); Description; It has a complete different meaning than in EN 16931

### ISSUE THREAD

**Issue by guascce** [eForms/eForms#51]
in EN : BT-10 "AN identifier assigned by the buyer for internal routing purpose. "

**Comment by guascce** [comment]
There should be an alignment between the e-invoicing terminology and the eForms terms.

**Comment by JachymHercher** [comment]
You are right, we should avoid using BTs in eForms that already have a different meaning in eInvoicing (just like in the ESPD). We will do a more detailed cross-check for such problems (along the lines of what we've done in #50). 

For BT-713, an alternative name could be "Contract Buyer Reference".

**Comment by JachymHercher** [comment]
We have done a more detailed check with @paulakeen and we have identified two other BTs that need renaming to be aligned with EN 16931: BT-506 should be renamed from Organisation Contact Email to Organisation Contact Email Adress and BT-503 should be renamed from Organisation Contact Telephone to Organisation Contact Telephone Number.
