### ISSUE TITLE
General: Clarification on when this consultation will be closed

### ISSUE THREAD

**Issue by karinmorild** [eForms/eForms#53]
The information about this consultation says it is open June – September 2018. Does it mean that the consultation will be closed at midnight between September 30 and October 1, or will it be closed at any other date/time?

**Comment by JachymHercher** [comment]
Indeed, the consultation will be open until the end of September (i.e. the midnight between September 30th and October 1st). Nevertheless, as far as possible, we would of course appreciate to receive comments sooner rather than later.
