### ISSUE TITLE
BT-ANY; PIN only; PIN social?

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#56]
Is there any successor notice for the current F21 prior information / F22 periodic indicative notice with ”call for competition“ unchecked?

**Comment by JachymHercher** [comment]
No. The idea is that PIN F1 and F4 are sufficiently "light" (and voluntary to use) that they could be used also for social services. Do you think that works? 

(The directives do not require F21 and F22 pin only either. These are rather an anomaly of the current standard forms.)

**Comment by tinne** [comment]
Thank you for this insight not obvious from the regulations.

The discussion whether ”it works“ could be lead from a data migration viewpoint, ”can an existing notice be published in the new form?“

- F21 PRI and F22 PER have section S1-03-00 (Communcation / Produrement documents), which seems to map to BT-13 Documents Restricted / BT-707 Documents Restricted Justification
  - Optional content of upcoming PIN only, so all right
- F04 is missing S2-02-13 Information about European Union funds as provided in F22 PER
  - This information would obviously been disposed as BG-61 EU Funds is not foreseen in PIN only
- Both F01 and F04 document S4-01-08 Information   about Government Procurement Agreement (GPA), which is missing from F21 PRI and F22 PER. This should map to BT-115 GPA Usage.
  - The information would have to be added for current social and other special securities prior information notices.

From this perspective, I see little friction. The remaining question would be: Do tenderers actually do provide procurement documents with PIN only notices?

**Comment by JachymHercher** [comment]
Concerning EU funds, yes, this information wouldn't be given. (I would say that their presence in F22 - without any conditions, cf. F21 - was an anomaly rather than intention.)

Concerning GPA, social notices are never covered by the GPA. We can reflect this better in the spreadsheet by changing M to CM for the Pin Only BT-115. (This will be analogous to the concessions GPA usage, which is CM because a concession can fall under the GPA only when it is a works concession.)

**Comment by tinne** [comment]
The remaining question would be: Do tenderers actually do provide procurement documents with PIN only notices?

**Comment by JachymHercher** [comment]
Good point, sorry. Most of the BT-15 (Documents URL) description actually doesn't apply to PIN buyer and PIN only, because the information should be given about the future URL where the documents _will_ be published, see 2014/24/EU Annex V Part B (I.2):

> Email or internet address at which the procurement documents _will_ be available for unrestricted and full direct access, free of charge.

To be in line with this obligation, we suggest the following description:

> Internet address for accessing procurement documents. _For all notices except PIN buyer and PIN only_, the address must give access that is direct (i.e. the exact webpage with the documents, not a general website), unrestricted (e.g. no payment, no registration) and full (i.e. the procurement documents must be complete). _For all notices except PIN buyer and PIN only_, the documents must be available already at the time of the publication of the notice.

**Comment by JachymHercher** [comment]
Linking PINs and CNs is already a legal obligation (see e.g. field IV.2.1 of [F2](http://simap.ted.europa.eu/documents/10184/99173/EN_F02.pdf)). This link is visible on TED under the "[document family](http://ted.europa.eu/udl?uri=TED:NOTICE:357002-2016:TEXT:EN:HTML&src=0&tabId=4)" tab. 

According to 2014/24/EU Art. 53(1), 

> "Contracting authorities shall by electronic means offer unrestricted and full direct access free of charge to the procurement documents from the date of publication of a notice in accordance with Article 51 or the date on which an invitation to confirm interest was sent. The text of the notice or the invitation to confirm interest shall specify the internet address at which the procurement documents are accessible." 


the case of "invitation to confirm interest" applies precisely to PIN time limit and PIN CFC (these two cases should definitely be treated the same). This could probably be made more nuanced, but for simplicity, I would tend to leave the URL as optional, but if the buyer already decides to submit it, then it needs to be "final" in the sense of being full, direct, unrestricted.

**Comment by tinne** [comment]
The backlink of CANs, CNs and corrections to previous notices is well known and understood.

Our users, however, are not obliged to use the same procurement system over the whole period of a tender and may well choose to change systems between them. Also, for some customers we only relay notices created in third-party (commercial) procurement systems.

In order to facilitate a proper national publication of the document family tab data we would therefore need the TED eSentool interface to provide a technical representation of the document family data for every notice published.

**Comment by JachymHercher** [comment]
@Annalisavacca, please see 

> In order to facilitate a proper national publication of the document family tab data we would therefore need the TED eSentool interface to provide a technical representation of the document family data for every notice published.

Is this something that the eSentool (or the planned API) is able to do / will be able to do?

**Comment by tinne** [comment]
Sorry, I was offline for some days. Is the question ”Is this something that the eSentool (or the planned API) is able to do / will be able to do?“ answered elsewhere?
