### ISSUE TITLE
BT-01 (Procedure Legal Basis) and other code fields; Data type; all legal bases in one?

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#57]
With the current SIMAP forms, there are nine distinct legal bases codes and one for ”other codes,“ which are specified separately in text form.

I wonder: would you suggest that any tendering legislation (including the national ones) should be combined in a single code system?

The same question applies to, possibly among others,
- BT-11 (Buyer Legal Type)
- BT-10 (Main Activity Authority)
- BT-610 (Main Activity Entity)
- BT-26 (Classification Type)
- BT-625 (Unit)

**Comment by JachymHercher** [comment]
I apologize, I'm not sure what you mean by a "single code system". Could you perhaps give an example or two?

**Comment by tinne** [comment]
The data type looks like it could set defined as a closed set { hearts, spades, suits, diamonds } (there is no fifth colour to our card games, and never will).

The data type we currently have are open sets { 2014/24/EU, 2014/25/EU, 2014/23/EU, 2009/81/EU , ... (further items), OTHER } with OTHER being defined by a separate BT Procedure Legal Basis Other Description.

Does this make at bit easier to understand?
