### ISSUE TITLE
BG-02 (Purpose); Description; lots-independent information

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#64]
This data group is not easy to understand as it intermixes lot specific and dedicatedly lot-indifferent information. Given I tender three lots. Do I give four Purpose sections, one for each lot and one ”general“ (with BT-137 Purpose Lot Identifier being NULL)? Otherwise,
- why is BT-23 (Main Nature) given in a lot specific section, when it must by its nature be identical with all lots?
- why is the BG-557 Estimated Maximum Value group given WITHIN a specific lot and how does it relate to the lot it is nested in?

Also, is it correct that all data up to row 54 (BT-95 Recurrency Description) belong to that lot-specific group?

**Comment by JachymHercher** [comment]
We agree this is a bit heavy - we've struggled with presenting this precisely yet simply. Nevertheless, "Do I give four Purpose sections, one for each lot and one ”general“ (with BT-137 Purpose Lot Identifier being NULL)?" is exactly right. 

The CMs then serve to specify what must/may be given per lot/per procedure/per both.

**Comment by tinne** [comment]
Thank you for explaining. Let me suggest to document this buy another level of nesting which declaratively rules out per-lot meaning for the per procedure only terms: [Purpose decomposition documentation.xlsx](https://github.com/eForms/eForms/files/2175970/Purpose.decomposition.documentation.xlsx)
