### ISSUE TITLE
BT-21 (Title); Repeatable; several titles but one description?

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#65]
Please explain why tenderers would specify several titles with a lot or procedure but only one BT-24 Description.

There is no distinction between single-line and multi-line texts like in the present forms, which seems to be a useful abstraction for the time being, but this might be a reason.

This issue may relate to #64 or not.

**Comment by JachymHercher** [comment]
This is a mistake, sorry, well spotted. BT-21 should not be repeatable. 

Indeed, at the level of the implementing regulation, we do not differentiate between single-line and multi-line text.
