### ISSUE TITLE
BT-53 (Options); social and concession and general; availability and conditions

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#66]
Can you please elaborate on the business rule in those cases when Options (and BT-54 Options Descriptions) are (conditionally) mandatory?

Is it right that you newly introduce Options for concession tenders and procedures of any legal basis for social and other special services?

**Comment by JachymHercher** [comment]
BT-54 (Options Description) should be mandatory conditionally on BT-53 (Options) being "Yes". BT-53 should not be conditionally mandatory, but simply mandatory - we apologize and will correct it. 

Yes, this is done to align the content of the different forms. For social forms, these fields are optional, so - depending on national/system preference - they don't even have to be seen by users.
