### ISSUE TITLE
BG-9 (Change); Description; General mechanism and date

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#72]
Regarding changes, do I understand you right when I expect that
- every time I need to publish a change in a notice (every time I today publish an F14 form or an updated form) I republish the original data and add ONE new Change section
- every record of the changes done before is retained
- the BT-141 Change Description contains in informal description of what I changed, BT-140 explains why.

Is this correct?

Why is there no general change date but only when procurement documents have changed (BT-719)?

**Comment by tinne** [comment]
Which means there is no history of general change dates in every notice but in case this information is needed, every single note of the past must be evaluated, right?

**Comment by JachymHercher** [comment]
Yes - to see the development and changes in the notice, one will have to go notice by notice. It doesn't sound that bad to us. Do you think it will cause excessive complications; could be solved better?

**Comment by tinne** [comment]
It could be easier to read if BG-9 had a separate BT Change Date, where the latest change would have Change Date = Notice Dispatch Date (after it has been assigned, see #58).

Also changes could be easily brought into order. Else, you could add a VT Change Revision counting changes explicitly.

**Comment by JachymHercher** [comment]
We will consider it, even though we try to rather err on the side of lesser fields and non-duplication. Just to be sure: a change is a notice, so every change date would equal to the notice dispatch date, correct? (I'm not sure what you mean by "latest").

Yes, this should be reliably possible with the TED dispatch / publication date.

**Comment by tinne** [comment]
Provided, the answer to #58 is ”the contracting body gives BT-05 and it is ok that it will not reach TED the same day in all cases“, every change date would equal to a notice dispatch date, yes.

If you introduced the other date field in #72 as well, every notice
- with a dispatch date equal to a change date is a change (aka F20 successor)
- with a dispatch date equal to a modification date is a modification (aka F14 successor)
- with a dispatch date unlike all of them will not have any change nor modification and is a ”new notice“

**Comment by tinne** [comment]
Regarding the discussion in #109, in order to have a sensible use of equality, the values in my comment of July 10th should all be timestamps (with time zone and minutes/seconds attached).

**Comment by tinne** [comment]
@JachymHercher You already said that ”every record of the changes done before is retained“ - this would mean BG-9 (and, likewise, BG-77) should be Repeatable Yes, shouldn't they?

**Comment by JachymHercher** [comment]
Hm, I don't think so. A change notice means, for example, republishing a CAN (with some changes). When another change notice is published, it changes the previous change notice (not the original CAN). This means the changes are retained in the body of the notice and only new changes need to be summarized in BG-9/BG-77.

**Comment by tinne** [comment]
What today is a F14 to an F20 would be a CAN with BG-77 and BG-9 filled, would it not?

Upon revision checks, I would have thought having an integrated change log (list of changes with dates, summary descriptions and reasons) would be much more readable that digging through a long list of notices.

**Comment by JachymHercher** [comment]
Yes. But that doesn't imply repeatability? 

Sure, that's definitely more readable. However, that can be done by an application (which goes through all the corrected CANs, compares them, etc.), it doesn't need to be in the data standard itself?

**Comment by tinne** [comment]
It does not. Just wanted to make sure I understand, as my previous interpretation proved wrong.

An application with all notices to a procedure would likewise. There are reasons that eSender clients do not know all notices (system / relay change, schema update / migration, data archiving). Thus, again an API for the ”document family“ page data query would enable them to do this without.

**Comment by JachymHercher** [comment]
Good point that not all publishers may have all the relevant notices. However, indeed, there should be an API available by the beginning of next year, so this need should be met.

**Comment by JachymHercher** [comment]
Based on further discussions, we have: 
- for better clarity, renamed Change to Change Cancellation.
- added BT-13716 (Change Previous Lot Reference) so that BT-140 (Change Reason Code) and other information can be given per lot.
- changed BG-09 to repeatable so that it be repeated in case of multiple lots.
