### ISSUE TITLE
BT-ALL; G-AP; Optional information always published?

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#75]
Perhaps this is just a documentary issue: In section 3.1.1 of the introductory paper, I would have expected to read the third bullet point as follows:

> Optional information. This information may be included in a notice, in which case it will be published (cf. footnote 5) on TED. 

Here, footnote 5 says that this piece of information can also be just recorded for internal / statistical use.

Is optional data always being published?

**Comment by JachymHercher** [comment]
Yes, optional data is always being published. The only data not being published (i.e. only for internal/statistical use) is the one marked for non-publication in BG-8 (Not Published). 

You are correct that the scope of BG-8 could be extended to any optional field. Do you think this would be used? Are there any field you would expect users to treat this way?

**Comment by tinne** [comment]
Upon rethinking, this seems to fine just the way it is.

**Comment by JachymHercher** [comment]
If you are willing to share your reasoning, we'd be interested to hear it? There was something to your proposal.

**Comment by JachymHercher** [comment]
Would there be some negative impact from publishing this information?

(I'm not sure whether "suitable for freelancers" goes into BT-76, as BT-76 is rather about an obligation to take a certain legal form.)

**Comment by tinne** [comment]
This seems to be unanswered for almost three months now.

We suggested to add a business term meaning, “the buyer suggests freelancers to bid for this procedure or lot.”

**Comment by JachymHercher** [comment]
We apologize for taking so long to reply. Since this seems to be a bit separate from the original topic of this issue, we have opened this topic under a new one - please see #171.
