### ISSUE TITLE
BT-501 (Organisation Identifier); Repeatable; should be changed to yes

### ISSUE THREAD

**Issue by JachymHercher** [eForms/eForms#77]
In the eForms webinar on 5th July, we noted that BT-501 should be repeatable, because one organisation might have (and might one to communicate) multiple identifiers.

**Comment by jurakova** [comment]
We don´t think that BT-501 should be repeatable, if organization can fill into the eForm just one Organization Identifier, it is sufficient.

**Comment by JachymHercher** [comment]
We agree that one organisation identifier is sufficient, in the sense that including more identifiers should not be an obligation. Nevertheless, if some organizations have reasons to include multiple (e.g. old and new; used for different purposes) we are not sure why to limit this option. Please note that marking the field as repeatable means that it "may" be repeated, not that it "must" be repeated.
