### ISSUE TITLE
BT-10/610 (Main Activity Authority/Entity); G-AP; Contracting organisation type

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#79]
In the 2018-07-05 regular webinar (as mentioned in section 6.2 of the consultation introduction), the Business Terms 10 and 610 were briefly discussed. They have been interpreted as successors to the current form sections S1-05 and S1-06, respectively.

Currently, procedures are restricted whether the contracting body can be a legal authority or entity. According to @JachymHercher this restriction will be relaxed as follows:

- Directive 2014/25/EU (sectoral): Contracting authority or entity (currently: entity only)

The other directives stay unchanged:

- Directive 2009/81/EU (defense): Contracting authority or entity
- Directive 2014/23/EU (concessions). Contracting authority or entity
- Directive 2014/24/EU (general): Contracting authority only

Can you confirm?

**Comment by JachymHercher** [comment]
I think the answer is "yes", but I would not call it relaxing a restriction, but rather using more precise terminology. Nothing in the law changes. This may perhaps clarify it further:
- Section I of the current sectoral directives always referred to "contracting entities", while in fact these can be contracting authorities or entities (see 2014/25/EU Art 3, Art. 4). 
- In eForms, we use the general word "buyer", which covers contracting authority/contracting entity/defence contractor/buyer awarding a contract subsidized by a contracting authority according to 2014/24/EU Art. 13. The precise type of buyer can be given in BT-11 (Buyer Legal Type). 
- BT-10 (Main Activity Authority), BT-610 (Main Activity Entity) will be mandatory depending on what is submitted in BT-11 and BT-01 (Procedure Legal Basis). For example, if BT-01 is sectoral directive and BT-11 is contracting authority, then both BT-10 and BT-11 will be mandatory.
