### ISSUE TITLE
BT-538 : duration code, codelist

### ISSUE THREAD

**Issue by MiraRatajczak** [eForms/eForms#82]
Can you give the codelist of this business term?

**Comment by tinne** [comment]
@muricna Are the translations in the code lists meant to be complete? How are they edited? Time period is at least missing the Austrian name of January (Jänner) and a German variant term of spring (Frühjahr).

**Comment by muricna** [comment]
The code lists are translated into the official languages of the European Union by our services.  The public procurement code lists are currently in the process of being devleopped.  We intend to reuse the time period code list.
