### ISSUE TITLE
BT-105: Procedure type, codelist

### ISSUE THREAD

**Issue by MiraRatajczak** [eForms/eForms#84]
Can you give us the code list, so that we can see how the national procedure needs to be introduced in the eForms?

**Comment by muricna** [comment]
The codes should represent:
Open   procedure
Restricted   procedure
Negotiated   procedure
Direct award
Competitive   dialogue
Innovation   partnership
Call for   expressions of interest
Vendor's list
Other single   stage procedure
Other multiple   stage procedure

**Comment by muricna** [comment]
The comment above has been updated
