### ISSUE TITLE
BG-6: How will the national procedure be implemented?

### ISSUE THREAD

**Issue by MiraRatajczak** [eForms/eForms#86]
Is only the field BT-88 filled in for national procedures or is there a possibility in the codelist of BT-155 to provide the name of the national procedure?

**Comment by JachymHercher** [comment]
We're intending BT-105 (Procedure Type) to only have a generic name (e.g. "Other procedure") and if this code is chosen, then BT-88 must contain a description. 

Having a codelist of all national procedures doesn't seem realistic... (They would also need to be harmonized across different EU countries etc.)
