### ISSUE TITLE
BG-702 and BG-701: The espd extension

### ISSUE THREAD

**Issue by MiraRatajczak** [eForms/eForms#87]
What does the ESPD extension look like? Do we need to give a summary of criteria both in the BG-702 and BG-701 as well as in the espd extension or in only either of them?

**Comment by eForms** [comment]
The ESPD extension has not yet been developed, but it should largely correspond to the latest version of the https://github.com/ESPD/ESPD-EDM. 

Only one - if the ESPD extension is used, then BG-701 and BG-702 will not need to be used.

(For info: @ec-mcs, @paulakeen)

**Comment by JachymHercher** [comment]
The ESPD extension has not yet been developed, but it should largely correspond to the latest version of the https://github.com/ESPD/ESPD-EDM.

Only one - if the ESPD extension is used, then BG-701 and BG-702 will not need to be used.

(For info: @ec-mcs, @paulakeen)
