### ISSUE TITLE
BT-Any: e-Invoicing is missing

### ISSUE THREAD

**Issue by MiraRatajczak** [eForms/eForms#88]
In the current forms in section   VI.2 you have a checkbox "Electronic invoicing will be accepted".   Is it intentional that this field is missing in the eForms?

**Comment by JachymHercher** [comment]
Yes, the idea is that by the time that eForms are expected to be implemented, accepting eInvoices will be fully mandatory as a result of the e-invoicing directive, so there will be no need to signal this in a notice.

However, it is true that eInvoicing will not be mandatory for below-threshold procurement. Do you think it is important to include this option to cater for below-threshold procurement? If yes, we would suggest to include it as a code for BT-107 (Techniques), which contains other similar information such as e-ordering.

**Comment by JachymHercher** [comment]
Yes, that can also be in BT-107. Similarly as for e-invoicing, needing to emphasize this is likely to be relevant only for below-threshold procurement and even there only in very rare cases.

**Comment by JachymHercher** [comment]
Correction: Based on further reflections, we have decided to take electronic invoicing, electronic ordering and electronic payment out of the BT-107 (Techniques) codes and rather implement them as separate BTs in BG-705 (Other Requirements and Terms). For more information, please see https://github.com/eForms/eForms/issues/29#issuecomment-400373268.

**Comment by JachymHercher** [comment]
In the light of the permissions codelist (#299, #300), the BT-743 (Electronic Invoicing) would also work better with it. We will suggest to change the description to "Whether tenderers will be required, allowed or not allowed to submit electronic invoices." and the data type from "indicator" to "code".
