### ISSUE TITLE
BT-707; Documents Restricted justification, codelist

### ISSUE THREAD

**Issue by MiraRatajczak** [eForms/eForms#89]
Can you give the codelist of this business term?

**Comment by muricna** [comment]
A common code list should represent Non-electronic communication justification:

1.	Tools, devices, or file formats not generally available
2.	Intellectual property right issues
3.	Buyer would need specialised office equipment
4.	Inclusion of a physical model
5.	Protection of particularly sensitive information

This code list can be used by BT 707 and BT-19.
