### ISSUE TITLE
BT-144 (Awarded Reason); Data type; Code list

### ISSUE THREAD

**Issue by MiraRatajczak** [eForms/eForms#91]
Can you give the codelist of this business term?

**Comment by muricna** [comment]
The code list covering Non-award could represent:

•	No tenders, requests to participate or projects were received
•	All tenders, requests to participate or projects were rejected
•	Decision of the buyer, because of insufficient funds
•	Decision of the buyer, because of a change in needs
•	Decision of the buyer, not following a tenderer's request to review the award, because of technical or procedural errors
•	Decision of the buyer following a tenderer's request to review the award 
•	Decision of a review body or another judicial body
•	Other reasons

**Comment by tinne** [comment]
Would “other reasons” be needed to be explained in a text field?

**Comment by JachymHercher** [comment]
So far, we are assuming that not. However, we are open to other opinions.

**Comment by JachymHercher** [comment]
We have received a request from Bulgaria to add the reasons for not awarding the contract from the Bulgarian legislation. It's listed below, together with our comments. We would propose to cover all such needs, even though the wording must be "standardised". 

Article 110. 
(1) The contracting entity shall terminate a procedure by a reasoned decision where:
1. not a single tender, request to participate or competing design has been submitted, or not a single participant has appeared for negotiations; **[covered by code 1]**
2. none of the tenders or requests to participate meet the conditions for submission, including form, manner and time limit, or all such tenders or requests are unsuitable; **[covered by code 2]**
3. none of the competing designs meet the conditions announced in advance by the contracting entity; **[covered by code 2]**
4. the highest ranked participant and the second highest ranked participant declines to conclude a contract; **[we proposed to add a new code covering this option: "The highest ranked tenderer(s) refused to sign the contract."]**
5. infringements are identified in the commencement and conduct of the procedure which cannot be corrected without this changing the conditions whereunder the procedure was announced; 
**[covered by 5 & 6]**
6. owing to non-fulfilment of any of the conditions referred to in Article 112 (1) herein, a public procurement contract is not concluded; **[not sure, more information needed]**
7. all tenders, which comply with the terms and conditions as announced in advance by the contracting entity, exceed the financial resources which the said entity can secure; **[covered by code 3]**
8. conducting the procedure or awarding the contract is no longer necessary as a result of a significant change in circumstances or where it is impossible to secure funding for the performance of the procurement for reasons which the contracting entity could not foresee; **[covered by code 3 & 4]**
9. the terms of the procurement as announced have to be subjected to substantial modifications that would alter the range of interested parties. **[covered by code 4]**

(2) The contracting entity may terminate the procedure by a reasoned decision where:
1. only one tender, request to participate or competing design has been submitted;
2. there is only one suitable request to participate or only one suitable tender;
3. there is only one competing design which meets the conditions announced in advance by the contracting entity;
**[we propose adding one code covering the three options above: "Only one admissible tender, request to participate or project was received."]**
4. the highest ranked participant:
(a) declines to conclude a contract; **[covered by the code proposed for Art. 110(4)]**
(b) fails to fulfil one of the conditions referred to in Article 112 (1) herein, or **[more information needed]**
(c) fails to prove that any grounds for exclusion from the procedure do not apply thereto. **seems similar to Art. 110 (2), more information needed**
