### ISSUE TITLE
BG-320: Winning Tender, tender information

### ISSUE THREAD

**Issue by MiraRatajczak** [eForms/eForms#92]
In Belgium we have a legal report after the opening of the tenders (Opening report). The report has information about who submitted tenders and who signed them (mandated person(s)). The buyer can decide if the publication of this report is visible for everybody, only for those who submitted a tender or for no one.

Can we use this business group for each tender with an indicator if this tender is a winning tender or not? Or can we create a national extension for the report?

**Comment by JachymHercher** [comment]
An extension for publishing information about all individual tenders is planned for eForms. This should be done via the extension mechanism mentioned in section 4 of the consultation introductory document. 

The work on the extension will be done at a later stage, but if you could list any BTs (besides those contained in BG-320) that you would like the extension to cover, we would appreciate it.
