### ISSUE TITLE
BT-1372 (Place Lot Reference); Description and G-AP; mandatory conditions and grouping

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#95]
What does CM mean with this BT? I would suppose it to be optional to denote one place for all lots.

Else or in addition, reference lot groups could be used to denote lots with a common performance place.

**Comment by JachymHercher** [comment]
CM means "mandatory if the BG-708 (Place of Performance) is included more than once in the notice" . If it appears only once, then BT-1372 does not need to be filled in. The same approach is used for other lot identifiers / references. 

Groups of lots could be used for such references, but we believe it would create too much complexity, so we left the references it in all (possible) cases just to individual lots.
