### ISSUE TITLE
BT-536 (Duration Start Date); Data type; allow relative start

### ISSUE THREAD

**Issue by tinne** [eForms/eForms#98]
Log running tendering procedures with e.g. participation competitions, several stages, etc. (not to mention in-court settlement) tend to get out of their planned time frames.

Reportedly, buyers therefore love the chance to publish a start date relative to an award date in order to save later need for amendments.

**Comment by JachymHercher** [comment]
We agree, this need is covered by BT-36 (Duration Period). For CNs, BT-536 (Duration Start Date) will not be mandatory if BT-36 is given. For CANs we think it should, as the contract will already be signed and thus the timing should be certain.
